### ISSUE TITLE
Custom Android Toast Message don't work

### ISSUE THREAD

**Issue by strukteon** [zhuowei/MCPELauncher#1047]
Making a new Toast Message with 'android.widget.Toast.makeText(com.mojang.minecraftpe.MainActivity.currentMainActivity.get(),"text",1).show()' doesn't work! There comes always an Error message: "Can't make handler in thread that has not called Looper.prepare()"
Please help or fix!

**Comment by LawRence-G-38** [comment]
Try adding `Looper.prepeare()` before the toast message function
