### ISSUE TITLE
blank

### ISSUE THREAD

**Issue by MCPEMaster65** [zhuowei/MCPELauncher#1103]
i was udate my mcpe to 0.15.0 version but when i open the blocklauncher its blank white and black please fix it

**Comment by zedman2000** [comment]
It has been stated over and over that BL has NOT been updated to 0.15 at this time.  Please close this issue.  The Author is working on this and stated that he is going to TRY to have compatibility by the end of this week.  I would rather he spend time working on Block Launcher than spend the time reading and closing this issue.  Please close this.
