### ISSUE TITLE
Everyone

### ISSUE THREAD

**Issue by pawsthehelper** [zhuowei/MCPELauncher#1133]
If your Minecraft is updated to .15 they will be fixing this issue by the end of the week  
Please close your issue if it of the same concept

**Comment by zedman2000** [comment]
@pawsthehelper Not that anyone is going to read this...but thanks for trying...I've been trying to help, but without being a moderator...only so much one can do...

**Comment by thejaustin** [comment]
@zedman2000 Well it's funny running into you here...
Also, I was actually about to tweet that Zhuowei needs some trusted moderators to help clean up the spam here.
