### ISSUE TITLE
Htc desire 826 crash on open

### ISSUE THREAD

**Issue by mhmdchico** [zhuowei/MCPELauncher#1143]
It crashes when i just open it and automaticly closes.
Plz fixxxxxx

**Comment by lolcraftboy** [comment]
a say dat y have the cras to on galexy note 4

**Comment by mhmdchico** [comment]
What? 
My devuce is htc desire 826 and when i open block launcher it crashes immediately.
Plz fix thus problem on next update

**Comment by GhostHuntermodz** [comment]
It crashes of you have 15.0 because it's not updated yet that are working on it 

If you want to go back to a version that works here is 14.3 
https://drive.google.com/file/d/0B0yUYMpSqV5bU2VHNGZfOXh4aEU/view?usp=drivesdk

**Comment by mhmdchico** [comment]
Tnx much

**Comment by zedman2000** [comment]
@mhmdchico please close this issue.  If you follow the author on Twitter, you would see this is being worked on.  To prevent him from spending time reading this and closing it vs spending time working on the app, please close this issue.

**Comment by PatrikXop** [comment]
Close the issuse!
