### ISSUE TITLE
Stop wasting time 

### ISSUE THREAD

**Issue by GhostHunterModz** [zhuowei/MCPELauncher#1150]
They are working in the 15.0 so stop spamming it doesn't work if you want 14.3 version of minecraft here it is but don't waste the author time https://drive.google.com/file/d/0B0yUYMpSqV5bU2VHNGZfOXh4aEU/view?usp=drivesdk

**Comment by lowjames** [comment]
Plz, close this report cause, were spending more time dealing with reports than porting BL!


Thx!

**Comment by zedman2000** [comment]
@GhostHuntermodz can you please close this issue so that Zhuowei does not have to spend time closing it?
