### ISSUE TITLE
Crashes instantly

### ISSUE THREAD

**Issue by HyunPaky** [zhuowei/MCPELauncher#1159]
It crashes as soon as i press on the app.i have a Samsung Galaxy A5 SM-A500FU

**Comment by peytontenno** [comment]
Same but I have a droid turbo and crashes instantly

**Comment by StacyPlays1002** [comment]
That happens to me to...

**Comment by abiel1912** [comment]
It happens to me too pls fix this

**Comment by lowjames** [comment]
Were working on it, sorry for the wait!

**Comment by lowjames** [comment]
Plz, close this report cause, were spending pore time dealing with reports than porting BL!


Thx!
