### ISSUE TITLE
BEFORE YOU CLICK ON 'New Issue' READ THIS!

### ISSUE THREAD

**Issue by Smasher535** [zhuowei/MCPELauncher#1170]
1. All INTEL users that got a pirated apk (from Aptoide etc.) it will not work! You need to buy the legacy one!

2. BlockLauncher isn't updated to 0.15.0.x, Zhuowei Zhang will try to update it TODAY! Wait for it, it takes time to rehook everything!!

3. STOP CREATING NEW STUPID ISSUES!

**Comment by jason82306** [comment]
Ya

**Comment by wilmpie123** [comment]
But then i van still see my status bar when i am playing

**Comment by bringito** [comment]
How long does it take to update for blocklauncher pro

**Comment by lowjames** [comment]
Dude, thares a pirated version on Amazon app store by "Apps"

**Comment by lowjames** [comment]
Plz, close this report cause, were spending pore time dealing with reports than porting BL!


Thx!
