### ISSUE TITLE
NOT COMPATIBLE WITH 15.0

### ISSUE THREAD

**Issue by lowjames** [zhuowei/MCPELauncher#1173]
It won't stop crashing after MCPE updated to 15.0

**Comment by pawsthehelper** [comment]
If your Minecraft is updated to .15 then they will be fixing this issue by the end of today hope this helps

**Comment by lowjames** [comment]
I hope it get fixed by tomarow

**Comment by staticshock8345** [comment]
It still doesint work at 11:38

**Comment by staticshock8345** [comment]
R u guys the ones working on it

**Comment by lowjames** [comment]
It still doesn't work

**Comment by staticshock8345** [comment]
Ok thx

**Comment by lowjames** [comment]
Were working restlessly to get it to work, plz be patient.

**Comment by lowjames** [comment]
Continue this in my other MSG about makeing blocklauncher work with the MCPE 15.1 update
