### ISSUE TITLE
PROGRESS REPORT

### ISSUE THREAD

**Issue by lowjames** [zhuowei/MCPELauncher#1185]
Stop Posting Issues! We are haveing trouble cause were spending more time dealing with with your complaints then porting and fixing BlockLauncher!

-BlockLauncher Support

**Comment by imnofox** [comment]
More importantly, why are you pretending to be "BlockLauncher Support"? 😕

**Comment by Thebeastincarnate** [comment]
Low James u close all yr issue

**Comment by lowjames** [comment]
I'm trying to tell people to stop reporting IN a report! And these by me arnt read by other support unless they actually want to!

**Comment by lowjames** [comment]
I'm the messenger

**Comment by jose-vm** [comment]
Kys

**Comment by Syntaxious** [comment]
Messenger? lmfao wat are u u stupid fuck

**Comment by Syntaxious** [comment]
i dont blame ur intelligent

u less intelligent, inferior being. your not support or a messager 

and like jose said, kys :) gday

**Comment by lowjames** [comment]
I am a messenger
