### ISSUE TITLE
Guys if you want to down grade look here 

### ISSUE THREAD

**Issue by GhostHunterModz** [zhuowei/MCPELauncher#1186]

**Comment by bringito** [comment]
Is it still compatible with mods

**Comment by staticshock8345** [comment]
Can u guys fix the problem or is there no way

**Comment by PatrikXop** [comment]
Yes you can play mods on 0.14 but not 0.15; since microsoft fucked it up so just w8 for update or downgrade to 0.14!

**Comment by staticshock8345** [comment]
Ok thanks

**Comment by lowjames** [comment]
Plz, close this report cause, were spending more time dealing with reports than porting BL!


Thx!

**Comment by GhostHuntermodz** [comment]
You are not helping stop acting like support

**Comment by lowjames** [comment]
Well neither are you!

**Comment by GhostHuntermodz** [comment]
Delete the world's or keep them so you can play in 15.0 later you upgrade

**Comment by lowjames** [comment]
I'm trying to speed us the progress on the update!

**Comment by lowjames** [comment]
???

**Comment by GhostHuntermodz** [comment]
No you are nit

**Comment by lowjames** [comment]
U lost me???
