### ISSUE TITLE
keeps crashing when I open it how do I fix it?????

### ISSUE THREAD

**Issue by catsrawesome** [zhuowei/MCPELauncher#1195]
#244

**Comment by lowjames** [comment]
You don't! Just wait! Hell it could take a year with everyone complaining!

**Comment by catsrawesome** [comment]
Ok

**Comment by lowjames** [comment]
Oh plz Lev this issue closed , were spending more time dealing with issues than fixing Blocklauncher.

Thx!

**Comment by catsrawesome** [comment]
DIVA
