### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by youssefhussein** [zhuowei/MCPELauncher#1352]
When i try to open the app it automatically crashes

**Comment by zedman2000** [comment]
Please close this, it has not been updated yet.  It is being worked on.  There are a few betas floating around, but they are incomplete.

**Comment by nightkiller745** [comment]
It keeps crashing

**Comment by laldld** [comment]
Every time i open the app it crashes every single time i open the app

**Comment by jcmodom1** [comment]
Hshshsjs

**Comment by jcmodom1** [comment]
Akqkakajaiakakwisjsjhshwsjjzjzn

**Comment by captphrank** [comment]
?

**Comment by captphrank** [comment]
Ok...

**Comment by zedman2000** [comment]
As was posted, it has not been updated, so unless you roll back your Minecraft to 0.14.3 or use the BlockLauncher beta, this is the expected behavior.  It is being worked on, in the mean time, close this as there are already issues open that this will be tracked against.

**Comment by zhuowei** [comment]
I know. Update is coming
