### ISSUE TITLE
Doesn't load for Motorola G3

### ISSUE THREAD

**Issue by XPGamer115** [zhuowei/MCPELauncher#1353]
When opening the app it will force close and say Block launcher has stopped for no reason?

**Comment by XPGamer115** [comment]
Android Version 6.0
Model number Motorola G3 (Generation 3)

**Comment by zedman2000** [comment]
what version of BL and Minecraft are you using?

**Comment by XPGamer115** [comment]
I am using Minecraft 0.15.3
And am using the latest version of Block launcher

**Comment by zedman2000** [comment]
And what version of BL is that?  There are newer versions than what is on the play store.

**Comment by XPGamer115** [comment]
The one on the Play store do I need to download a apk?
On 26 Jul 2016 7:25 p.m., "Daniel Rozwood" <notifications@github.com> wrote:

And what version of BL is that? There are newer versions than what is on
the play store.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/zhuowei/MCPELauncher/issues/1353#issuecomment-235359902>,
or mute the thread

**Comment by zedman2000** [comment]
If you are signed up for beta testing, the version you get from the play store is different than not.  If you have 1.12.8, that is not compatible with 0.15.x, so it crashes EXACTLY as you described.

**Comment by XPGamer115** [comment]
I get now thank you got it working :)

**Comment by zedman2000** [comment]
Please close this issue, thanks

**Comment by DownloadFreeAPK** [comment]
BL 1.17b1
MCPE 1.2.0.31

**Comment by zhuowei** [comment]
@downloadFreeAPK you need 1.17b2.

**Comment by DownloadFreeAPK** [comment]
You installed BL 1.17b2

**Comment by zhuowei** [comment]
@downloadfreeapk does the latest beta (http://tinyw.in/bl) work?
