### ISSUE TITLE
Not all built in textures can be used 

### ISSUE THREAD

**Issue by zedman2000** [zhuowei/MCPELauncher#1400]
Using 1.13 Pro from the Google Play Store.
When using the built in "names" for textures, some of the names do not appear to work.  I have a mod where:
var x=["quartz_block",2];
var y=...whatever other thing I used
Block.defineBlock(id,"Name",[x,x,y,y,y,y],2,true); is used to define the block.

The failure happens with the quartz_block.  Works in 0.12.8, not in 0.13.  If I change to other things like "mushroom_block" everything is AOK, although now I have mushroom pieces instead of quartz based pieces!

**Comment by DiegoGTRatty** [comment]
Now this is how you use the issue tracker.

**Comment by ck1988** [comment]
Agreed @zedman2000 have found any good mods for mcpe I've been trying to find a few good ones that I loved that I can't find any actually working mods

The ones that I am looking for
1. Carpenter's blocks
2. Biomes a plenty
3. Quarry
4. Factorization
5. Ores overload (was one that had 50+ different ores)
And there are some mods that I am actually looking for a mcpe version of just look up sl1pg8r on YouTube and watch all of the Minecraft modded game play and let me know when you have found all of the Minecraft mods they are using for the pocket edition I'd love to play some modded mcpe with you guys/gals

**Comment by Black-DeathPE** [comment]
BlockLauncher is using 0.14's texture index still. For example, the latest name for the blue stained clay: hardened_clay_stained_blue is for 0.16.0, however you still have to use "stained_clay", (2 or 3 can't remember) like 0.14.0

**Comment by zedman2000** [comment]
@Black-DeathPE thanks for that, however as I said, I used quartz_block, which is listed under the 0.14 website list of texture names [http://zhuoweizhang.net/mcpetexturenames/].  Also, as stated, that works fine under 0.14 (0.12.8).  0.15 versions (BL 0.13) does not like that name.  Are you aware if there is a new name for quartz?  I would imagine that from what you are saying, there very well could be - although SOME ended up the same as indicated in my first post (mushroom_block)

**Comment by Black-DeathPE** [comment]
Hmm, odd, maybe give these a try?: quartz_block_bottom, quartz_block_side and quartz_block_top

Those are the texture names in 0.16

**Comment by zedman2000** [comment]
Well, that worked!
@Black-DeathPE Where did you get the list of names for 0.16?  I'll leave this open until you reply for your easy access to reply.  Then I'll close this!

Thanks!

**Comment by zedman2000** [comment]
@Black-DeathPE is this the list you pulled that name from?
http://www.minecraftforum.net/forums/minecraft-pocket-edition/mcpe-mods-tools/mcpe-mod-tool-discussion/1987699-texture-names-modpe-custom-blocks

Thanks!
