### ISSUE TITLE
Server.sendChat() broke

### ISSUE THREAD

**Issue by KenMizz** [zhuowei/MCPELauncher#1408]
plz fix it:)

**Comment by WIPocket** [comment]
I havent noticed it breaking...
Too many ppl used cheats so scripting was disabled for multiplayer.

**Comment by KenMizz** [comment]
@WIPocket before the function broke,i used for auto login

**Comment by WIPocket** [comment]
I did that too (before they made autologin on server-side a thing), but now the script doesnt get executed. Read the popup when connecting to a server sometime...
