### ISSUE TITLE
Block.defineBlock

### ISSUE THREAD

**Issue by LightsDawn** [zhuowei/MCPELauncher#1416]
This is my code I use:
Block.defineBlock(150, "Compressed Cobblestone", "cobblestone");

What am I doing wrong? Says can't bring string to number. I'm confused.

**Comment by MineExplorer** [comment]
Texture must be named ["cobblestone", 0]

**Comment by LightsDawn** [comment]
Getting the same error even with that

**Comment by LightsDawn** [comment]
I figured it out. I was doing something else that was wrong. Was trying a watercolor don't know how it works yet

**Comment by ISAAC300** [comment]
Block.define(200,"Compressed stone",["cobblestone",0],0,false,1);
