### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by TundraArcher** [zhuowei/MCPELauncher#1432]
The latest beta crashes on x86 devices when I try opening the app.

Android: 4.4.2

**Comment by SaccyScriptor** [comment]
As previously stated by Zhowei, this launcher may not work on some Jellybean devices (Android 4.4). You need to be more specific with the phone, version and any other problem related items. If you will not, you need to close this issue.

**Comment by TundraArcher** [comment]
Android 4.1-4.3 = Jellybean
Android 4.4 = KitKat

The crash is already fixed in the latest beta.

**Comment by SaccyYLP** [comment]
I don't understand why typed that, it further proves my point, xD
