### ISSUE TITLE
What is Entity.setExtraData(); do?

### ISSUE THREAD

**Issue by KenMizz** [zhuowei/MCPELauncher#1434]
can anyone tell me?

**Comment by WIPocket** [comment]
Set the entityes NBT tag. Not sure about its syntax, but things like {CustomNameVisible:0} are possible (for making jeb sheeps or Dinnerbone/Grumm entityes that dont show the nametag).

Also I am not sure if this is an issue exactly....

**Comment by KenMizz** [comment]
thx
