### ISSUE TITLE
Bug: showParticle on addEffect is not working

### ISSUE THREAD

**Issue by FunIsDangerous** [zhuowei/MCPELauncher#1439]
Not showing the particles on an effect is currently not possible

example: doing: 

`		Entity.addEffect(Player.getEntity(),MobEffect.digSpeed,40,4,false,false);
`

will show particles, even though the it's set to false

**Comment by Johnmacrocraft** [comment]
Duplicate with #253

**Comment by FunIsDangerous** [comment]
Oh well, my bad. Thanks for pointing out
