### ISSUE TITLE
modTick() ... what happened?

### ISSUE THREAD

**Issue by SaccyScriptor** [zhuowei/MCPELauncher#1447]
I'm pretty sure modTick worked while you weren't inside a world before? What happened? and how can replace/fix it?

**Comment by like2omg** [comment]
If you understand the basics of the game, a "tick" is meant to be while in-game. If it used to happen while not, it was a bug and now fixed. (I don't see trying to iterate through all entities in the world making sense if the entities, and the world, are not even loaded.)

There are events for when a world loads up as well as when a world is exited (manually, as any means of not closing the world manually, like the device ran out of battery, will make that event not fire).

**Comment by SaccyScriptor** [comment]
Of course I understood this but I just asked that question to be informed. Due to this question NOT being an issue I shall close it. I think the modTick for outside gameplay got removed in the MCPE app and not in BlockLauncher thus making it a question/issue irrelevant to this project.
