### ISSUE TITLE
Moto G4 Play will see Minecraft white screen then crash

### ISSUE THREAD

**Issue by craftablescience** [zhuowei/MCPELauncher#1466]
My Moto G4 Play can run BlockLauncher with no mods or texture packs, but when a mod is applied it will only show "Minecraft" with a white background then crash.

**Comment by zhuowei** [comment]
which mod? Do you have a link to the mod?

**Comment by blewis14** [comment]
Yes, it is the latest version of DesnoGuns

**Comment by zhuowei** [comment]
@blewis14 I can't reproduce it on my device (Huawei Nexus 6P). Can you take a bug report after the crash, upload it to Google Drive, and post the link here? https://www.youtube.com/watch?v=YxQ3NTloD2c

**Comment by blewis14** [comment]
Sorry about the delay, I'll get around to it on the weekend.

**Comment by blewis14** [comment]
Here you go:
[bugreport-2017-12-02-14-16-58.zip](https://drive.google.com/file/d/1Ec2fM8XOeAhV6wA34y_ecY8HNndBqrQu/view?usp=sharing)

**Comment by blewis14** [comment]
@zhuowei If you are not working on this issue I can close it
