### ISSUE TITLE
Textures not working

### ISSUE THREAD

**Issue by paperbenni** [zhuowei/MCPELauncher#1473]
# [Here's the problematic modpkg](https://github.com/zhuowei/MCPELauncher/files/1785449/modbuild.zip)
Hello, I am working on a pretty big ModPE project and wanted to run a quick test. Blocklauncher immediatly crashed when importing the modpkg, no error message whatsoever, crashlog is empty. I added some try catch statements that returned a bunch of missing icons. I didn't change the name of the files or something in the script regarding the icons. I have absolutely no idea what to do now. Could that be a bug or is there something wrong with my mod? Pleeaase, I need help!
The attached file is a renamed modpkg since github issues don't support modpkg files.

**Comment by Hanprogramer** [comment]
Me too. I think this is a bug from version 1.4.4 minecraft pe

**Comment by zedman2000** [comment]
If your mod is too large for the memory / device you are running on, it will crash.  I have seen this many times in the past.  That is, the script would not run on one phone, but it would run on another without issue.

**Comment by paperbenni** [comment]
@zedman2000 With 16x16 pngs I didn't think that memory could ever become an issue at all. I mean you need hundreds of them to even take up the memory a normal photo would. What does the game have to load in order to hit on memory that hard?!

**Comment by zedman2000** [comment]
No idea.  I can only say that in the past, if I loaded too many texture packs, it would bust things.
That's why for my mods, I used specific types of texturing so I limit the amount of textures I loaded.
Used to work with @zhuowei with this way back when...Just saying try it with less textures and see what happens.

**Comment by Hanprogramer** [comment]
This is working now, it is fixed. Pls close the issue
