### ISSUE TITLE
14 step in Building (Readmi.md) error

### ISSUE THREAD

**Issue by Dreanei** [zhuowei/MCPELauncher#1478]
![image](https://user-images.githubusercontent.com/22614547/40053883-9bc72efe-584b-11e8-9125-9096073487ce.png)
![image](https://user-images.githubusercontent.com/22614547/40053909-b3654294-584b-11e8-8263-0c8bbc98ce2c.png)
Maybe it's my mistake. Would be nice if you explain it ☺

**Comment by zhuowei** [comment]
@Dreanei you may need an older Android SDK version that includes the `android` command. This repository hasn't been updated for years, and so still has the old Ant-based compilation tools, which the SDK that comes with Android Studio no longer supports.
