### ISSUE TITLE
Any Custom textures immediately crashed the bl

### ISSUE THREAD

**Issue by Hanprogramer** [zhuowei/MCPELauncher#1480]
I am just trying to use custom textures for item but crashes the game as soon as i used ModPe.setItem then entered the world. maybe it has something to do with the libminecraftpe.so file?

P. S. Is this just happened to my os? Arm mali android 7.1

**Comment by zhuowei** [comment]
@Hanprogramer Can you post a link to your code? Also, can you take a bug report (https://www.youtube.com/watch?v=YxQ3NTloD2c), upload the log to Google Drive, and paste the link here?

**Comment by Hanprogramer** [comment]
Ummmm.... hello?

**Comment by Hanprogramer** [comment]
Edit: bug is fixed. Good to go now!
