### ISSUE TITLE
Coordinate functions mixed

### ISSUE THREAD

**Issue by 7thShark** [zhuowei/MCPELauncher#1488]
Blocklauncher Pro Beta 1.23.2
MCPE Version 1.10.0.7

- MCPE X = Blocklauncher's Y
- MCPE Y = Blocklauncher's Z
- MCPE Z = Blocklauncher's X

![SmartSelect_20190319-164206_Gallery](https://user-images.githubusercontent.com/8009936/54640480-466a4500-4a66-11e9-81ed-d477b58b9c73.jpg)

**Comment by zhuowei** [comment]
@7thShark Thanks for the report! Should be fixed in the new beta.
