### ISSUE TITLE
MC 1.12 crash (logcat)

### ISSUE THREAD

**Issue by CtrlAltCuteness** [zhuowei/MCPELauncher#1498]
I loaded a file dynamically into my script, but this also happens when I don't use a separate file as well as when I add it dynamically via. code while it is running.
This crash I am experiencing is about a second or two after the text shows via. `ModPE.showTipMessage()` (side note: your client now limits text entry field sizes which it used to not do ... separate bug?)

I have been monitoring if `hud_screen` is the active screen before I am having this message show up, so it cannot be stockpiled messages (which I think is what vanilla does for all `/title` slots).
```logcat
F/libc    ( 7567): Fatal signal 11 (SIGSEGV), code 1, fault addr 0x52c in tid 7808 (Thread-244330)
I/DEBUG   (  328): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
I/DEBUG   (  328): Build fingerprint: 'samsung/trltespr/trltespr:5.1.1/*****/*************:user/release-keys'
I/DEBUG   (  328): Revision: '12'
I/DEBUG   (  328): ABI: 'arm'
I/DEBUG   (  328): pid: 7567, tid: 7808, name: Thread-244330  >>> net.zhuoweizhang.mcpelauncher.pro <<<
I/DEBUG   (  328): signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x52c
I/DEBUG   (  328):     r0 00001f02  r1 00000000  r2 0000003b  r3 7887cdb0
I/DEBUG   (  328):     r4 00001f02  r5 aec59800  r6 85f8a354  r7 7887b5d0
I/DEBUG   (  328):     r8 7887b688  r9 856b73ec  sl 7887b5d0  fp 85f8a354
I/DEBUG   (  328):     ip b6d4ae04  sp 7887b4a0  lr b6cfac81  pc b6ce4b24  cpsr 600f0010
I/DEBUG   (  328): 
I/DEBUG   (  328): backtrace:
I/DEBUG   (  328):     #00 pc 00004b24  /system/lib/libGLESv1_CM.so (glGetString+32)
I/DEBUG   (  328):     #01 pc 032e7111  /data/data/net.zhuoweizhang.mcpelauncher.pro/app_patched/libminecraftpe_text_section (deleted)
```
Build fingerprint manually censored (ask if necessary and I'll provide over Twitter DMs)

**Comment by zhuowei** [comment]
That seems like a Vanilla Minecraft bug? I'm not touching anything in the graphics pipeline.

**Comment by CtrlAltCuteness** [comment]
I'll plop it on the JIRA
