### ISSUE TITLE
Unfortunately the version of Minecraft PE on this device is not compatible with BlockLauncher. 

### ISSUE THREAD

**Issue by xMistt** [zhuowei/MCPELauncher#1500]
Whenever I run BlockLauncher I get:

`Unfortunately the version of Minecraft PE on this device is not compatible with BlockLauncher. Please install Minecraft PE for ARM processors. (You probably didn't purchase Minecraft: if that is the case, buy a legitimate version of Minecraft, which will be compatible with ARM processors)`

I'm running the latest versions of Minecraft & Block Launcher from the app store.

**Comment by KenMizz** [comment]
You just gonna wait for the new version support

**Comment by xMistt** [comment]
> You just gonna wait for the new version support

Oh, BlockLauncher isn't updated to 1.12.1.1 yet?

**Comment by KenMizz** [comment]
> 
> 
> > You just gonna wait for the new version support
> 
> Oh, BlockLauncher isn't updated to 1.12.1.1 yet?

I don't think so, it does not work for me too, please check @zhuowei twitter for any update

**Comment by Davixk** [comment]
you guys realize the last update is from over 5 years ago right??

**Comment by KenMizz** [comment]
@Davixk It's not open source anymore, but it's still updating
