### ISSUE TITLE
An update?

### ISSUE THREAD

**Issue by Andrea-Miele** [zhuowei/MCPELauncher#1509]
@zhuowei Is this project discontinued? Why is not updated to Minecraft 1.16?

**Comment by ItzCrazyBuddy** [comment]
I need the update

**Comment by an0rmal1st** [comment]
Yeah 1.16-1.17 updates

**Comment by protectoryt** [comment]
Yup

**Comment by Andrea-Miele** [comment]
I'm closing this issue because @zhuowei is not working on blocklauncher anymore
