### ISSUE TITLE
How did you find out the method to unlock Mojang scripting? 

### ISSUE THREAD

**Issue by TripleCamera** [zhuowei/MCPELauncher#1511]
Hi, zhuowei. I am trying to unlock Mojang scripting in 1.16, and I have studied [your code](https://github.com/zhuowei/MCPELauncher/blob/master/jni/prepatch.cpp):  
```cpp
static bool bl_AppPlatform_supportsScripting_hook(void* self) {
	__android_log_print(ANDROID_LOG_ERROR, "BlockLauncher", "scripting hook");
	return true;
}
static bool (*bl_ScriptEngine_isScriptingEnabled_real)();
static bool bl_ScriptEngine_isScriptingEnabled_hook() {
	bool realret = bl_ScriptEngine_isScriptingEnabled_real();
	//__android_log_print(ANDROID_LOG_ERROR, "BlockLauncher", "script engine hook: overriding %s with true", realret? "true" : "false");
	//v8Init();
	return true;
}
static bool (*bl_FeatureToggles_isEnabled_real)(void* toggles, int id);
static bool bl_FeatureToggles_isEnabled_hook(void* toggles, int id) {
	//__android_log_print(ANDROID_LOG_ERROR, "BlockLauncher", "feature enabled? %d", id);
	if (id == 9) return true;
	if (id == 7) return true;
	return bl_FeatureToggles_isEnabled_real(toggles, id);
}

static bool bl_hbui_Feature_isEnabled_hook(void* feature) {
	//__android_log_print(ANDROID_LOG_ERROR, "BlockLauncher", "hbui feature enabled");
	return true;
}
```
I wonder how you found out the way of unlocking Mojang scripting. How did you find out these 4 functions to hook? And why did you enable feature 9 and 7?  
By the way, is there anything I should pay attention to in 1.16? Do I have to edit that code to make it work properly? Thanks.

**Comment by Andrea-Miele** [comment]
@zhuowei Yes how did you unlock? @zhuowei

**Comment by TripleCamera** [comment]
@zhuowei [I have hooked a lot of functions](https://github.com/listerily/ModdedBE/commit/d9900efb02a8acd9ad8f1283d5d83cee2124d209), so that all these functions **always** return `true` now:  
 - `AppPlatform::supportsScripting`  
 - `AppPlatform_android::supportsScripting`  
 - `ClientInstance::isScriptingEnabled`  
 - `Experiments::Scripting`  
 - `FeatureToggles::isEnabled`  
 - `ScriptEngine::isScriptingEnabled`  
 - `hbui::Feature::isEnabled`  

Now I can enter worlds with scripts, but the scripts **are not working**. I don't know what is missing. Could you help me?

**Comment by Andrea-Miele** [comment]
@zhuowei I know you're not working on this project anymore, but at least give the necessary information for making a new similar project like Modded BE

**Comment by TripleCamera** [comment]
> @ zhuowei I know you're not working on this project anymore, but at least give the necessary information for making a new similar project like Modded BE

Maybe we shouldn't @ him so many times... He is probably busy these days.

**Comment by zhuowei** [comment]
I do keep an eye on these issues, and no, hooking those methods was enough on 1.13 and below, not sure what changed.

**Comment by Andrea-Miele** [comment]
Can you make blocklauncher open source for all the versions?

**Comment by ProtectorYT364** [comment]
Woah he actually replied

**Comment by JRBros2346** [comment]
@TripleCamera if you developed the app please post the link here i can use it

**Comment by TripleCamera** [comment]
Well, actually, Mojang has removed Scripting(aka **Additional Modding Capabilities**) in [Beta 1.18.20.21](https://feedback.minecraft.net/hc/en-us/articles/4423151445901). I guess there is no need to keep this issue open, so I will close it very soon. 

> @ TripleCamera if you developed the app please post the link here i can use it

I don't think it is polite to promote my app here. You can check out my profile for more info.

**Comment by TripleCamera** [comment]
I'm going to close it **now**. The issue list is so crowded.
