### ISSUE TITLE
Server.getAddress() returns null all the time

### ISSUE THREAD

**Issue by ZhyMC** [zhuowei/MCPELauncher#194]
卓伟大大肯定会汉语。

我发现我在调用Server.getAddress()时候无论怎样都会返回null。

我尝试在newLevel事件中使用它，加入一个服务器后它返回null。

然后我又尝试使用Mobtick事件，在加入服务器30tick后查询服务器的地址，还是null。

我用pe的gui写了一个按钮，触发它输出Server.getAddress()的返回结果。

各种试，还是null。

我启动器的版本是1.8.2测试版。PE版本是0.10.4正式版。

望解决，谢谢。

**Comment by PEMapModder** [comment]
Actually not many people know Chinese.

**Comment by OniOniOn-** [comment]
@PEMapModder Zhuo Wei Chinese will certainly greatly.

I found my calling Server.getAddress () no matter what time will return null.

I try to use it in newLevel event, adding a server after it returns null.

Then I try to use Mobtick event, after joining a server 30tick query server address, or null.

I used to write a pe of gui button to trigger its output Server.getAddress () returns the result.

A variety of test, or null.

My starter version is 1.8.2 beta. PE version is the official version 0.10.4.

Wang, thank you.

**Comment by zhuowei** [comment]
Fixed in 1.8.7.
