### ISSUE TITLE
color chat not works

### ISSUE THREAD

**Issue by xpyctum** [zhuowei/MCPELauncher#200]
I'm trying to get color chat using blocklauncher, but colors not works. No multipkayer, no singleplayer

**Comment by zhuowei** [comment]
Is ModPE scripts enabled?

**Comment by xpyctum** [comment]
@zhuowei Yes

**Comment by Insane96MCP** [comment]
It works for me

**Comment by xpyctum** [comment]
@Insane96MCP how you test colors?

**Comment by Insane96MCP** [comment]
Both with ChatColor.COLOR and §color_number

**Comment by zhuowei** [comment]
I'm guessing this is fixed?

**Comment by Insane96MCP** [comment]
Yep, is fixed
