### ISSUE TITLE
The Manage Addons Menu is Broken

### ISSUE THREAD

**Issue by martyrboy** [zhuowei/MCPELauncher#208]
There is no import button.

![screenshot_2015-02-28-10-27-59](https://cloud.githubusercontent.com/assets/3254231/6427422/2255e81a-bf35-11e4-8575-dc5f0e703157.png)

**Comment by OniOniOn-** [comment]
You don't import them... You should install .apk files yourself... Not using features that you don't know for sure is probably a good idea...

**Comment by zhuowei** [comment]
I could add an Import button, but it'll be the same as installing the APK yourself. Do you want that?

**Comment by martyrboy** [comment]
No. I just didn't understand how addons worked.

I renamed the addon .zip to an .apk and was happy to find that it was indeed an installable package.
