### ISSUE TITLE
i cant change skins the 2nd time

### ISSUE THREAD

**Issue by xSnowyAngel** [zhuowei/MCPELauncher#212]
Hi, ummm is it me or i cant change skin for the second time when i upload it to multiplayer. I found another skin that i liked but when i uploaded it to multiplayer it stills show the same old skin before...

**Comment by xSnowyAngel** [comment]
Plsss help

**Comment by zhuowei** [comment]
Skins may take up to 4 hours to update.

**Comment by zhuowei** [comment]
Closing: skins server is no longer being used.
