### ISSUE TITLE
Fnaf fan game

### ISSUE THREAD

**Issue by YOLOmodder** [zhuowei/MCPELauncher#217]

**Comment by sliceofcode** [comment]
This shouldn't be here.

**Comment by zhuowei** [comment]
You can use the game engine built into Blender (which is fairly limited), or you could export models and levels to a game engine. Popular free game engines for hobbyists are Unreal Engine and Unity, and both have extensive tutorials online.

I don't actually know how to make a 3D game though, so I'm probably not the best person to ask about this.

**Comment by YOLOmodder** [comment]
I didn't mean to post this here...
