### ISSUE TITLE
Entity.removeEffect(entity, id) doesn't remove particles of the effect

### ISSUE THREAD

**Issue by Desno365** [zhuowei/MCPELauncher#241]
How to reproduce:
Use Entity.addEffect(Player.getEntity(), id, duration, amplification, ambient, showParticles) with showPaticles = true
After a short time use Entity.removeEffect(Player.getEntity(), id) with the same id. The animation with particles of the effect remain and they continue until the users exit the game.

This thing seems to not happen with Entity.removeAllEffects(): particles with this method are correctly removed.

Using Minecraft PE 0.11.1 with BL 1.9.7

**Comment by RandomAltThing** [comment]
Its Minecraft PE not Minecraft

**Comment by Desno365** [comment]
PE was implied.
But I updated the comment

**Comment by Desno365** [comment]
Seems to be fixed using MCPE 0.14.2
