### ISSUE TITLE
BlockID range increase?

### ISSUE THREAD

**Issue by zedman2000** [zhuowei/MCPELauncher#257]
I know that the item id range was changed to 4096 for the latest release.  Is there a possibility to increase the block id range as well?

**Comment by RandomAltThing** [comment]
Not possible

**Comment by zedman2000** [comment]
@RandomAltThing Thanks for telling me know, Is this a limitation of BL or of MCPE itself?

**Comment by RandomAltThing** [comment]
@zedman2000 Not sure, I was told they would have to completely rework block ids or whatever. Ask @zhuowei

**Comment by zhuowei** [comment]
MCPE world format doesn't support more than 256 block IDs; need to store extra IDs in a separate file (like Spoutcraft) or overhaul the world format (like Minecraft Desktop's Anvil format)

**Comment by RandomAltThing** [comment]
I knew I had heard that somewhere

**Comment by zedman2000** [comment]
Understood!  Thanks!  That is very interesting, but after @RandomAltThing mentioned it, I looked at the PC list of items and saw that it ALSO has a similar (if not the same) limit.
I really appreciate that @zhuowei and @RandomAltThing for the education.  Also, thanks for Block Launcher!  It really is awesome and I really enjoy MCPE with this!  I can't wait for the .12 PRO to be released!  Joystick support!!!
