### ISSUE TITLE
EntityRenderType for cow is incorrect

### ISSUE THREAD

**Issue by duggum** [zhuowei/MCPELauncher#282]
__BlockLauncher Pro v1.10.3__
__MCPE v0.12.2__

The render type id for cow (7) is incorrect. It should be 6; 7 is for Mooshrooms.
Run the following code and look at a cow to confirm:
```javascript
var ctx = com.mojang.minecraftpe.MainActivity.currentMainActivity.get();
function modTick() {
  if (ctx != null) {
    ctx.runOnUiThread(new java.lang.Runnable({
      run: function() {
        try {
          // this prints 6 if you look at a cow; 7 for a mooshroom
          ModPE.showTipMessage(Entity.getRenderType(Player.getPointedEntity()));
        } catch (err) {
          print(err);
        }
      }
    }));
  }
}
```
![cows](https://cloud.githubusercontent.com/assets/6613807/10447999/883ba03c-7157-11e5-9dff-6b7244a78299.png)

**Comment by sliceofcode** [comment]
Might be off topic, but why are you running this in the UI thread?

**Comment by duggum** [comment]
@sliceofcode The code and images above are just a means of demonstrating that the EntityRenderType for 'cow' is 6, not '7' as it is assigned in EntityRenderType.cow.

The code I was running that brought this to my attention is:
```javascript
// make all pigs look like cows
function entityAddedHook(entity) {
  if (Entity.getEntityTypeId(entity) === EntityType.PIG) {
    Entity.setRenderType(entity, EntityRenderType.cow);
  }
}
```
I was just running some test code to help me learn the API, and I was surprised to see all new pigs rendering as Mooshrooms, not Cows.

**Comment by zhuowei** [comment]
re UI thread: yeah, please don't run that on the UI thread (technically all Minecraft methods should be accessed on game thread, not UI thread; however, I don't think Minecraft cares)
Thank you so much - fixed in latest beta.
