### ISSUE TITLE
Crash in Mashmellow

### ISSUE THREAD

**Issue by BasixKOR** [zhuowei/MCPELauncher#284]

**Comment by sliceofcode** [comment]
@BasicStudyer Marshmallow is not yet supported.

**Comment by zhuowei** [comment]
I can't reproduce in the Android 6.0 emulator - which device do you have? I know Nexus 9 crashes

**Comment by BasicStudyer** [comment]
I have Nexus 5.

**Comment by sheradrax** [comment]
I also have this issue, running android 6.0 on a beta cm13 for snapdragon processor Note 3 variants.

**Comment by BasicStudyer** [comment]
use old live patching code, not crash.

**Comment by zhuowei** [comment]
@BasixKOR oh really? I'll try defaulting 6.0 to the old code and see what happens.

**Comment by zhuowei** [comment]
Please test http://zhuoweizhang.net/MCPELauncher/MCPELauncherApp-release-beta.apk - it is able to run Pokecube PE on my Nexus 6P running Android 6.0.1

**Comment by BasixKOR** [comment]
It works!
