### ISSUE TITLE
custom mobs health

### ISSUE THREAD

**Issue by Izaac9236** [zhuowei/MCPELauncher#287]
Entity.setHealth(ent,int); is not working in custom mobs fix this thanks zhuowei for example function useItem(x,y,z,i){
if(i==id){
mb = Level.spawnMob(x,y+1,z,EntityType.BAT);
Entity.setHealth(mb,5000); //not working
}}

**Comment by zhuowei** [comment]
Fixed in latest version: do Entity.setMaxHealth(mb, 5000) to raise a mob's max health
