### ISSUE TITLE
Request Level.getSpawnerEntityType(x, y, z) function for ModPE

### ISSUE THREAD

**Issue by Clagdriff** [zhuowei/MCPELauncher#296]
I hope this is not the false place to write this. I wanted to request the function Level.getSpawnerEntityType(x, y, z), it should return the EntityType of the Spanwer at x, y, z.

**Comment by officialmcpro32** [comment]
But we also need Level.setSpawner (x,y,z,block){}

**Comment by Clagdriff** [comment]
No, we don't need Level.setSpawner(), because with Level.setTile(x, y, z, Id, Data) you can place a spawner and with Level.setSpawnerEntityTypeId(x, y, z, EntityTypeId) you can make it an active Spawner.

**Comment by zhuowei** [comment]
Added - thanks.
