### ISSUE TITLE
Crashes when using Player.addItemInventory(itemId,amount);

### ISSUE THREAD

**Issue by VCraft** [zhuowei/MCPELauncher#304]
If I use Player.addItemInventory(200,amount); doesn't crash, because 200 is a block id. But if I use Player.addItemInventory(600,amount); it crashes. Because 600 is an item id.
I hope that you fix it as soon as you can. Thanks!

**Comment by zhuowei** [comment]
Was fixed in beta 4 - should work now. 

also, it wasn't crashing because it was an item ID; it was crashing because it was greater than 512. BlockLauncher patches MCPE to support more than 512 IDs, but I missed a patch, so MCPE dies when trying to draw the icon for an item with an id above 512.
