### ISSUE TITLE
Pitch and Yaw are reversed in BL 1.11 beta 4

### ISSUE THREAD

**Issue by Desno365** [zhuowei/MCPELauncher#305]
Pitch and Yaw are reversed: getPitch() returns player's Yaw and getYaw() returns player's Pitch

Edit: also Entity.setRot() is reversed. Before was Entity.setRot(entity, yaw, pitch) now it seems to be Entity.setRot(entity, pitch, yaw). Can you please restore it to default?

**Comment by duggum** [comment]
Ditto on this issue.

**Comment by zhuowei** [comment]
lol what will look into this

**Comment by zhuowei** [comment]
Fixed in release.
