### ISSUE TITLE
ModPE.setFov() doesn't work in BL 1.11 beta 4

### ISSUE THREAD

**Issue by Desno365** [zhuowei/MCPELauncher#306]
Read title ^

**Comment by ReventonMC** [comment]
yeah.. it doesnt work...

(wait r u really desno? wow... the gun mod maker.. wow)
hellloooo....!

**Comment by zhuowei** [comment]
Was disabled since I didn't get a chance to fix it; should be fine now.
(Also, thank you so much for filing all these issues)

**Comment by Desno365** [comment]
Glad to help you :)
