### ISSUE TITLE
Item.defineArmor() doesn't work in BL 1.11 beta 4

### ISSUE THREAD

**Issue by Desno365** [zhuowei/MCPELauncher#307]
Item.defineArmor(id, iconName, iconIndex, name, texture, damageReduceAmount, maxDamage, armorType) doesn't work with the latest beta. The item added with this function are not displayed at all in the armor inventory in survival.

**Comment by zhuowei** [comment]
This is a known issue - didn't have time to fix setFoodItem or armor items, so just made them define regular items instead. Will fix in the release after this one.

**Comment by zhuowei** [comment]
Fixed in latest beta.
