### ISSUE TITLE
Item.addShapedRecipe() doesn't work in BL 1.11 beta 4

### ISSUE THREAD

**Issue by Desno365** [zhuowei/MCPELauncher#308]
Read title ^

**Comment by zhuowei** [comment]
I have no idea what's going on here, so I'll leave this for the next release :(

**Comment by zhuowei** [comment]
I think I fixed the issue (I had an extra `!` in a piece of code, lol) but I haven't tested it. I would appreciate it if you can try the latest beta

**Comment by Desno365** [comment]
Can confirm that it works in the latest beta.
