### ISSUE TITLE
When will BlockLauncher support scripts for 0.13.0?

### ISSUE THREAD

**Issue by AigarEnotov** [zhuowei/MCPELauncher#309]
I want to start writing ModPE scripts, but BlockLauncher doesn't support scripts for MCPE 0.13.0. When will it support them?

**Comment by AigarEnotov** [comment]
Please, answer!

**Comment by PocketEdition-Miner** [comment]
He recently released a beta, http://tinyw.in/bl

**Comment by AigarEnotov** [comment]
Thank you!

**Comment by zhuowei** [comment]
Soon (this week) - sorry about the delay.

**Comment by AigarEnotov** [comment]
OK. Thank you for all your work. Without BlockLauncher, everyone couldn't use ModPE.
