### ISSUE TITLE
Some custom items look like they are enchanted but they are not

### ISSUE THREAD

**Issue by Desno365** [zhuowei/MCPELauncher#310]
Some custom items have the enchanted animation on the icon for apparently no reason. 
Screenshoot:
![](https://pbs.twimg.com/media/CUllX9VWoAAUxR6.png:large)

Edit: found what caused it: the function to blame is Item.setHandEquipped()

**Comment by zhuowei** [comment]
I'm closing this since you opened a new issue - thanks.
