### ISSUE TITLE
[0.12] Armor legging layer appear in the chestplate area

### ISSUE THREAD

**Issue by ShadowMine64** [zhuowei/MCPELauncher#313]
Wierd right :/

**Comment by zhuowei** [comment]
I think this is a known bug - 0.13 doesn't even have custom armor support yet; will look at it again when that's added back

**Comment by zhuowei** [comment]
Does this still happen in the latest beta on 0.13?

**Comment by ShadowMine64** [comment]
Nope but someone is having texture problems

**Comment by zhuowei** [comment]
Closing this one: is there a different issue for the texture problems?

**Comment by ShadowMine64** [comment]
He says that Blocklauncher is causing texture problems, they work fine for me so I thought I'd put it out there just in case
