### ISSUE TITLE
The entityAddedHook

### ISSUE THREAD

**Issue by ReventonMC** [zhuowei/MCPELauncher#315]
it worked perfectly with 0.12, but in 0.13 it doesnt work.
function entityAddedHook(e){
if(Entity.getEntityTypeId(e)==63){ // if the entitytype is a multiplayer human
clientMessage("another player joined");
}}
so this thing works when I join, but when other person joins my world it doesnt work

**Comment by zhuowei** [comment]
Yeah, I didn't hook up the add player hook since I didn't think anyone was using it... clearly I'm wrong. Should be fixed now.
