### ISSUE TITLE
Adding custom blocks to the Creative inventory makes the game crash when the inventory is opened (BL 1.11 stable)

### ISSUE THREAD

**Issue by Desno365** [zhuowei/MCPELauncher#319]
I tried adding a custom block to the Creative inventory with Player.addItemCreativeInv() in the latest Blocklauncher (1.11 stable) and this causes a crash everytime I try to open the Creative inventory.

**Comment by zhuowei** [comment]
So this only happens with blocks, not items, right?

**Comment by Desno365** [comment]
Yes, items work perfectly. Adding blocks causes this crash.

**Comment by KairusDarkSeeker** [comment]
@zhuowei you should've released BlockLauncher 1.11 in December so that you could fix all bugs

**Comment by zhuowei** [comment]
Should be fixed in the latest beta - give it a try?

**Comment by Desno365** [comment]
In the latest beta (1.11 beta 3) this bug doesn't seem to be fixed. Items work while adding just a simple block makes the game crash when opening the inventory. 

Tried with two blocks with this code:
```javascript
// cubes
const CUBE_NORMAL_ID = 232;
Block.newBlock(CUBE_NORMAL_ID, "Cube", "cubenormal");
Block.setDestroyTime(CUBE_NORMAL_ID, 1);

const CUBE_COMPANION_ID = 233;
Block.newBlock(CUBE_COMPANION_ID, "Companion Cube", "cubecompanion");
Block.setDestroyTime(CUBE_COMPANION_ID, 1);
```
And using Player.addItemCreativeInv() with these two blocks (and some items too) in newLevel.

**Comment by Desno365** [comment]
Forgot to say that Block.newBlock it's a custom function to catch texture pack errors. It just act like Block.defineBlock:
```javascript
Block.newBlock = function(id, name, textureNames, sourceId, opaque, renderType)
{
	try
	{
		Block.defineBlock(id, name, textureNames, sourceId, opaque, renderType);
	} catch(e)
	{
		// user hasn't installed the texture pack
		if(!textureUiShowed)
			pleaseInstallTextureUI();

		Block.defineBlock(id, name, "enchanting_table_top", sourceId, opaque, renderType);
	}
}
```

**Comment by Desno365** [comment]
@zhuowei I tried your piston mod and it add blocks in creative without any crash. But I don't know why my blocks make the game crash. Tried also to move the code from newLevel to outside any function like you did, but it didn't work.

**Comment by Desno365** [comment]
This is a little test mod I did with only one block and it make the game crashes.
Really don't know why https://gist.github.com/Desno365/697d58021d8f3f3c5229

**Comment by Desno365** [comment]
After 100 and more tries, I figured out that adding a block to the creative inventory without setting the item category makes the game crash. So the code that I just needed to add was Item.setCategory(CUBE_COMPANION_ID, ItemCategory.TOOL);

**Comment by KairusDarkSeeker** [comment]
there is no latest beta linked @zhuowei
