### ISSUE TITLE
Entity.getAll() broken.

### ISSUE THREAD

**Issue by SuprD** [zhuowei/MCPELauncher#327]

**Comment by SuprD** [comment]
Yep, it doesn't work. Just gives this error (see screenshot).
![screenshot_2015-11-26-10-53-20](https://cloud.githubusercontent.com/assets/16037311/11429379/f7755a0a-942b-11e5-95f7-b7bb0dcaaf88.png)

**Comment by duggum** [comment]
I just ran the following command in game and it printed all entity ids for me:

```javascript
for (var i in Entity.getAll()) { clientMessage(i); }
```

**Comment by zhuowei** [comment]
Script example please?

**Comment by SuprD** [comment]
function procCmd (cmd) {
   if (cmd=="count") {
      number = 0;
      allEntities = Entity.getAll();
      for (var i = 0; i < allEntities.length(); i++) {
         if (Entity.getEntityTypeId(allEntities[i])==EntityType.PIG_ZOMBIE) {
            number += 1;
         }
      }
      clientMessage(number);
   }
}
This should count all the pigmen, but fails. The popup says line 4 is the issue.

**Comment by duggum** [comment]
This worked for me.I had 17 pig zombies in the Nether.

```javascript
var pz = 0;
var ents = Entity.getAll();
for (var i in ents) {
  if (Entity.getEntityTypeId(ents[i]) === EntityType.PIG_ZOMBIE) { pz++; }
}
clientMessage("Number of Pig Zombies: " + pz);
```

**Comment by SuprD** [comment]
Oh ok, duggum's code works for me, so Entity.getAll() isn't broken. What's strange to me is that my method used to work, but doesn't now.

**Comment by zhuowei** [comment]
I'll check if getAll used to return something else - it might've returned a list before

**Comment by zhuowei** [comment]
It's `allEntities.length` not `allEntities.length()` I think?

**Comment by SuprD** [comment]
Yup, that was the problem. My bad, I should've looked carefully for that. It's working like before now. :)
