### ISSUE TITLE
custom blocks place in water has been destroy by water

### ISSUE THREAD

**Issue by Izaac9236** [zhuowei/MCPELauncher#333]
custom blocks destroy in water fix this

**Comment by zhuowei** [comment]
It looks like melting in water is now determined by the material of the block:

`Block.defineBlock(199,"Duckstone Torch",[["redstone_torch_on",0]],1 /* use the same material as the stone block */,false);` doesn't melt in water

`Block.defineBlock(199,"Duckstone Torch",[["redstone_torch_on",0]],5 /* use the same material as a torch */,false);` does melt in water

Is this different behaviour from 0.12?

**Comment by Izaac9236** [comment]
i not used this, Block.defineBlock(210," block",[["stone",0]],0);

**Comment by zhuowei** [comment]
hmm. Will take a look.

**Comment by Izaac9236** [comment]
close issues
