### ISSUE TITLE
New Block.Newclonedblock( blockid to clone, new block id);

### ISSUE THREAD

**Issue by Godsoft029** [zhuowei/MCPELauncher#335]
To reproduce water

**Comment by Godsoft029** [comment]
Or to reproduce portal blocks

**Comment by s3r1alpari4h** [comment]
Just use define block with the same texture as water or portal

**Comment by Godsoft029** [comment]
But the block diesen has the water ai. E.g It wont flow

**Comment by s3r1alpari4h** [comment]
Try setting the renderType

**Comment by KairusDarkSeeker** [comment]
Please guys this isn`t an issue, report an issue and suggest a feature on @zhuowei 's twitter
