### ISSUE TITLE
Entity.rideAnimal() crashes Blocklauncher

### ISSUE THREAD

**Issue by Desno365** [zhuowei/MCPELauncher#338]
Tried to use Entity.rideAnimal() in the latest beta for 0.13 and it crashes Blocklauncher. I used it with a villager that would have ridden a minecart.

**Comment by s3r1alpari4h** [comment]
Crashes for me. I used me riding a creeper.

**Comment by KairusDarkSeeker** [comment]
me too i was using ` Entity.rideAnimal() ` in a creeper riding an ocelot so it would be an Ocelot Jockey :)

**Comment by Johnmacrocraft** [comment]
Yes his bug report is right, Zhuowei Zhang. If you try to use Entity.rideAnimal() it will crash your game (blocklauncher) at all entities.

This bug only happens BlockLauncher for 0.13.0 version. Blocklauncher for 0.12.x doesn't have this bug.

Wait, Desno365???

**Comment by s3r1alpari4h** [comment]
Lol

Looks like you're popular desno.

**Comment by KairusDarkSeeker** [comment]
just shut up

**Comment by KairusDarkSeeker** [comment]
desno can you please tell me what input type on android.widget.EditText turns into a password

**Comment by s3r1alpari4h** [comment]
Dude do you have anger issues or something?

I didn't even say anything to you

**Comment by KairusDarkSeeker** [comment]
sorry I was a little confused that time because I have my device broken :<

**Comment by tombailey** [comment]
@zhuowei any update on this?

**Comment by sero583** [comment]
@KariusDarkSeeker i mean if you want to make a EditText into a password type, just easily read the Doc's from Google.

**Comment by KairusDarkSeeker** [comment]
where?

**Comment by sero583** [comment]
@KariusDarkSeeker First the Docs are at developer.android.com and Samuel i think made a .txt Data which get uploaded and the highest will be shown.

**Comment by sero583** [comment]
I meant @KairuDarkSeeker

**Comment by sero583** [comment]
I meant @KariusDarkSeeker ...

**Comment by sero583** [comment]
Last one @KairusDarkSeeker , hope it works now!

**Comment by zhuowei** [comment]
Fixed

**Comment by KairusDarkSeeker** [comment]
Thx hope my mod doesnt crash or it'll be a crap
