### ISSUE TITLE
Entity. getMobSkin is not working [BUG]

### ISSUE THREAD

**Issue by officialmcpro32** [zhuowei/MCPELauncher#343]
Entity.getMobSkin(victim)=="mob/villager/librarian ");

**Comment by officialmcpro32** [comment]
I used it with if(

**Comment by s3r1alpari4h** [comment]
I think you did your script wrong.

**Comment by KairusDarkSeeker** [comment]
@s3r1alpari4h #h3 its not wrong idiot it certainly is a bug

**Comment by s3r1alpari4h** [comment]
@KairusDarkSeeker Woah don't call me an idiot.

**Comment by KairusDarkSeeker** [comment]
ok i wont, are u a beginner in JS?

**Comment by s3r1alpari4h** [comment]
JavaScript is easy af. I only do MCPE mods in my spare time. I'm usually using languages like PHP, Java, Python and C

**Comment by zhuowei** [comment]
It *is* a bug; it's another case where I thought nobody would ever use that method so didn't bother updating it for 0.13.

**Comment by zhuowei** [comment]
Fixed - try the latest beta.

**Comment by KairusDarkSeeker** [comment]
lol i dont see any 1.11.1 in the play store
