### ISSUE TITLE
When you hit a mob the sound is random

### ISSUE THREAD

**Issue by s3r1alpari4h** [zhuowei/MCPELauncher#344]
The title says it.
I'm on the latest beta of BlockLauncher and Minecraft PE 0.13.0 official.

**Comment by s3r1alpari4h** [comment]
When I hit a cow I heard the wold hit sound and then I hit a cow again and heard the zombie sound and the same thing happens on other mobs.

**Comment by s3r1alpari4h** [comment]
Wolf*

**Comment by s3r1alpari4h** [comment]
I heard the nether sound when I hit a enderman...

**Comment by s3r1alpari4h** [comment]
Also the spawn sound is random this is like the biggest bug ever..

**Comment by zhuowei** [comment]
Sound is working fine for me: which texture pack, which version of Android?

**Comment by PocketEdition-Miner** [comment]
I had this when I ported my texture pack to 0.13; you haven't updated the sounds for 0.13 in your texture pack. Extract the sounds from an 0.13 apk and put those into your texture pack or delete the sounds folder of your texture pack.

**Comment by s3r1alpari4h** [comment]
I'm not using a texture pack at all

**Comment by s3r1alpari4h** [comment]
I just updated to the latest beta and cleared data .. Isn't doing it anymore
Odd
