### ISSUE TITLE
Entity.setCape() should not be removed

### ISSUE THREAD

**Issue by KairusDarkSeeker** [zhuowei/MCPELauncher#345]
# Please @zhuowei bring Entity.setCape() back please

**Comment by s3r1alpari4h** [comment]
Its still there in the latest beta afaik

**Comment by zhuowei** [comment]
No it's not. It's been removed; the method is there so existing scripts won't crash; it does nothing

**Comment by KairusDarkSeeker** [comment]
why?

**Comment by KenMizz** [comment]
@zhuowei if We can setCape to the entity,It will be fun
