### ISSUE TITLE
Doesn't opens 

### ISSUE THREAD

**Issue by krampuushd** [zhuowei/MCPELauncher#348]
I just installed BlockLauncher and when I'm going to open it it stays all black and sends me back to my homescreen . Help please

KrampuusHD

**Comment by PocketEdition-Miner** [comment]
@zhuowei can only help if you provide Android device and version

**Comment by krampuushd** [comment]
Lg l3 e-400 , Android version 2.3.6

KrampuusHD

**Comment by krampuushd** [comment]
@zhuowei Lg l3 e-400 , Android version 2.3.6

KrampuusHD
