### ISSUE TITLE
Custom items and blocks duplicate or triplicate in the creative inventory

### ISSUE THREAD

**Issue by TheViictor** [zhuowei/MCPELauncher#354]
![screenshot_2015-11-29-10-02-56](https://cloud.githubusercontent.com/assets/11732684/11456184/2c9d5abe-9681-11e5-9df5-31fc8f4b4661.png)
When using Player.addItemCreativeInv it appears the item in the creative inventory, but that item or block can be duplicated or triplicated!

**Comment by Sime69** [comment]
restart your block launcher :) 
1- 🔧
2- active or not active texture pack
3- active or not active texture pack... again! 
4- back :)

**Comment by zhuowei** [comment]
This is fixed in the latest versions.
