### ISSUE TITLE
Crashes, when world is loaded

### ISSUE THREAD

**Issue by ingvaras** [zhuowei/MCPELauncher#355]
Block launcher crashes when the world is loaded. There are a lot of methods called (6000 lines of not stupid code) in my mod and it worked perfectly with 0.12.3. http://www98.zippyshare.com/d/Macwv0D2/870548/Pokedroid . My mod is installable with app, just hit "play", "install mod".

**Comment by krampuushd** [comment]
Your need do write your androud device and version only like that can @zhuoweizhang can help you

**Comment by ingvaras** [comment]
It doesnt work on all android devices.

**Comment by zhuowei** [comment]
Sure, I'll take a look.

**Comment by ShadowMine64** [comment]
Hm.. I get the same thing with my device, 
Specs- 
Andriod 4.4.4 XT1080 model

**Comment by ingvaras** [comment]
Have you fixed it?

**Comment by ShadowMine64** [comment]
Nope

**Comment by zhuowei** [comment]
Turns out this is a duplicate with #346: I forgot to update transparent model parts for the entity renderer API, so any custom entity renderer that passed true to transparent in setTextureOffset crashes the game. Fixed in 1.11.1.
