### ISSUE TITLE
Player.getPointedVec() issue

### ISSUE THREAD

**Issue by KairusDarkSeeker** [zhuowei/MCPELauncher#364]
Player.getPointedVec() is really that I wanted i thought that it would work when the player is pointed to a direction and it functions when i point to a block

**Comment by zhuowei** [comment]
If you just need to know which way the player is facing, use getYaw and getPitch. If you need it in vector form you can convert it easily: see https://github.com/zhuowei/ModPEScripts/blob/master/500ise_paintbrush.js#L133

**Comment by KairusDarkSeeker** [comment]
I already know that please do it
