### ISSUE TITLE
crashes when opening blocklauncher

### ISSUE THREAD

**Issue by Infinyx** [zhuowei/MCPELauncher#366]
Crashes when opening blocklauncher, when i got to safe mode its fixed, but when i return to normal it crashes again :(

**Comment by zhuowei** [comment]
Which device? Intel Atom devices (e.g. Zenfone, Hudl2) aren't working yet

**Comment by Infinyx** [comment]
Android 4.4.4

**Comment by Infinyx** [comment]
Alright its working now, thanks :)
