### ISSUE TITLE
BUG? function startDestroyBlock(x,y,z,side){} is not working.

### ISSUE THREAD

**Issue by Yroki12** [zhuowei/MCPELauncher#368]
//code
function startDestroyBlock(x,y,z,side){
var lg=Level.getTile(x,y,z);
var c=0; c++
if(lg==1){
Entity.setHealth(getPlayerEnt(),0);
                }  }
I wrote it, but it wasn't work. But no error.
Is it a bug?

**Comment by Khristian-kun** [comment]
thats because it only works when you start, not while destroying block, maybe @zhuowei has do add a hook called function whileDestroyBlock(x,y,z,side,progress);

**Comment by zhuowei** [comment]
Sorry about that! this is a known issue: duplicate of #326.

**Comment by Yroki12** [comment]
I see. Thx both:)

**Comment by Yroki12** [comment]
@Khristian-kun 
I can't use that code
