### ISSUE TITLE
Mobs without brains?

### ISSUE THREAD

**Issue by zedman2000** [zhuowei/MCPELauncher#370]
Is it possible to setup a method or something to create a passive mob that does NOT respond to anything around them?  Right now we can create mobs (awesome!), but they are based on the game engines for whatever mob you pick,  Be it a spider, creeper, or the default villager.

I appreciate that we have methods to try to freeze the mobs in place, but they still spin around even if you can get them to stand still.

I would like to create a mob that only does what I tell them.  One that requires my code to do anything.

Thanks for such an awesome enhancement to Minecraft!

**Comment by Godsoft029** [comment]
Or something like on pc the command summon nbt tag NoAi

**Comment by zedman2000** [comment]
Awesome!  Added as an enhancement!  Thanks @zhuowei !
I know this is going to help one of my mods, but big time it is going to help the Mechanics mod (cars/bikes/etc.).

**Comment by zhuowei** [comment]
added Entity.setImmobile, which completely freezes the entity; will look into disabling the AI portion only.

**Comment by zedman2000** [comment]
Thanks!  This is awesome!
