### ISSUE TITLE
Please support Intel processor device!

### ISSUE THREAD

**Issue by Gene1024768** [zhuowei/MCPELauncher#373]
It can't work on Intel devices like Zenfone5!

**Comment by PocketEdition-Miner** [comment]
Trust me; Zhuowei knows about this. I don't know why it isn't fixed, maybe the way BlockLauncher patches MCPE would never work on an Intel device.

**Comment by Sigreth** [comment]
Acer Icona One 8, which has Intel, can't support this. Any idea how long until support will arrive?
