### ISSUE TITLE
Mobs turn into cows after restart

### ISSUE THREAD

**Issue by ingvaras** [zhuowei/MCPELauncher#380]
After you restart block launcher and load the world you played before, you get this http://imgur.com/ltZPONB . This is really annoying in mob depended mods. Maybe in next update you could make that when the world is loaded, all the mobs are being destroyed (and leave no meat, please)?

**Comment by PocketEdition-Miner** [comment]
This is down to the mod developer to fix, however could be an enhancement for Zhuowei to add. Simply could save all entities and on load re-set their render types.

**Comment by ingvaras** [comment]
Maybe there is a method like this:

Entity.setHealth(getAllMobs(id), 0)

Cause saving all the stuff and then reseting all the mobs is "a bit" complicated

**Comment by KairusDarkSeeker** [comment]
thats still not fixed

**Comment by zhuowei** [comment]
Skins now persist, and render types will save if the mod author adds a renderer.name attribute to the renderer

**Comment by KairusDarkSeeker** [comment]
How do u use it?
