### ISSUE TITLE
Entity.getRenderType returns 0

### ISSUE THREAD

**Issue by Black-DeathPE** [zhuowei/MCPELauncher#381]
function newLevel()
{
clientMessage("Mod Morph By §4Pitchula Gamer");}

function attackHook(attacker, victim) {
if(Player.getCarriedItem() == 352) {
var rend = Entity.getRenderType(victim);

var skin = Entity.getMobSkin(victim);

Entity.setRenderType(Player.getEntity(),rend);
Entity.setMobSkin(Player.getEntity(),skin);

if(rend === 9) {
 
 }
 else if(rend === 18) {
 
 }
 }
 
}

This is an error found by Pitchula, he kept receiving errors saying render type 0 does not exist when setting render.

**Comment by zhuowei** [comment]
This is fixed in latest beta.
