### ISSUE TITLE
Level.destroyBlock still havent been fixed? 

### ISSUE THREAD

**Issue by QmodsX** [zhuowei/MCPELauncher#385]
var goldId = 41;

function redstoneUpdateHook(x,y,z,newCurrent, worldLoading, blockId, blockDamage){
	var powered = newCurrent;
	if(blockId == goldId && powered >=1 && powered <= 15){
		Level.destroyBlock(x,y,z,true);
	}
}

No working for me :(

**Comment by zhuowei** [comment]
Redstone currents only work for custom blocks, not built in blocks.
