### ISSUE TITLE
Blocklauncher Pro crashing when importing textures - 13.0

### ISSUE THREAD

**Issue by Dankscrub** [zhuowei/MCPELauncher#386]
[blocklauncher_crash_1449344068.txt](https://github.com/zhuowei/MCPELauncher/files/52945/blocklauncher_crash_1449344068.txt)
When importing textures on a Kindle Fire HD7 4 running Fire OS 4.5.5, Blocklauncher Pro will either crash or go into safe mode. Upon attempting to leave safe mode, it crashes again. I've tried clearing the cache and reinstalling several times. 

EDIT: When I get it to work, the textures are corrupt. It's every texture pack.

**Comment by zhuowei** [comment]
One of your texture packs has an old terrain.meta that's not compatible with 0.13.1. Please make sure that your texture packs are compatible.
