### ISSUE TITLE
Me Can't Open In Free Minecraft version 

### ISSUE THREAD

**Issue by RayTheBlockHunter** [zhuowei/MCPELauncher#388]
If Open It Blank Or Crash Please Fix It For android v2.3.6

**Comment by Dankscrub** [comment]
Blocklauncher is for the full version only.

**Comment by ambrewgaming** [comment]
I have the full version and it gose blank when i open it and then crashes

**Comment by zhuowei** [comment]
Android 2.3 is no longer supported. The MCPE Demo version is not supported by BlockLauncher at all.

**Comment by RayTheBlockHunter** [comment]
why :(
 

    On Tuesday, December 8, 2015 8:14 AM, zhuowei <notifications@github.com> wrote:
 

 Android 2.3 is no longer supported. The MCPE Demo version is not supported by BlockLauncher at all.—

**Comment by jose-vm** [comment]
Close this issue

**Comment by zhuowei** [comment]
I fixed one issue that may be crashing 2.3, but since I don't have a 2.3 device I'm not supporting 2.3. Closing.

**Comment by RayTheBlockHunter** [comment]
huhuhuhu 

    On Friday, January 15, 2016 9:11 AM, zhuowei <notifications@github.com> wrote:
 

 I fixed one issue that may be crashing 2.3, but since I don't have a 2.3 device I'm not supporting 2.3. Closing.—
