### ISSUE TITLE
Make doors openable and closable

### ISSUE THREAD

**Issue by PocketEdition-Miner** [zhuowei/MCPELauncher#402]
This could be achieved by a function such as Level.toggleDoor(x, y, z); You could probably also make this work for chests and furnaces etc, which in that case could be Level.runBlockEvent(x, y, z);

**Comment by zedman2000** [comment]
Door can already do this.  Just set the data bit that and the Minecraft Engine will do this for you.
http://minecraft.gamepedia.com/Door

See the section on Data Values.

**Comment by zedman2000** [comment]
@PocketEdition-Miner suggest you close this one.

**Comment by PocketEdition-Miner** [comment]
Okay thanks - didn't know I could do that.

**Comment by PocketEdition-Miner** [comment]
Okay thanks - didn't know I could do that.
