### ISSUE TITLE
hideparticles in `Effect.addEffect` not working

### ISSUE THREAD

**Issue by Johnmacrocraft** [zhuowei/MCPELauncher#404]
`Entity.addEffect(getPlayerEnt(), 1, 99999, 99999, false, true);`
When I use hideparticles in `Entity.addEffect` like this (example), it doesn't hide particles.

**Comment by jose-vm** [comment]
I don't think it's a BL bug but a MCPE one @zhuowei

**Comment by Johnmacrocraft** [comment]
Already reported by other one, and I don't think it needs to be opened until now.

**Comment by ISAAC300** [comment]
You can "re-make" the function with this code:
Level.addParticle = function(id,x,y,z,a,b,c,size){
return Level.addParticle(id,0,0,0,0,0,0,0);
}

**Comment by Johnmacrocraft** [comment]
Wait, the number of this issue is 404. LOL
