### ISSUE TITLE
ModPE Script, that work on LOCAL (not External like play.lbsg.net).

### ISSUE THREAD

**Issue by sero583** [zhuowei/MCPELauncher#407]
That, it gaves a function or check box in Settings from BlockLauncher, which will called "Scripts from other Clients will work on your hosted Server", this would be cool and fun for the Users :)

**Comment by KairusDarkSeeker** [comment]
yep it will be cool too if the custom items&blocks are visible to each other

**Comment by DiegoGTRatty** [comment]
Actually there is a temporal fix to that.

Lets say you have a sword mod like... this:

<code>ModPE.setItem(700, "withersword", 0, "Wither Sword", 1);

function attackHook(a, v) {
player = Player.getEntity();
item = Player.getCarriedItem();
if (item == 700) {
if (v == player) {
Entity.addEffect(v, MobEffect.wither, 5*20, 3, false, true);
}
}
}</code>

Obviously your friend can't see the sword, but if you hit him, he will get the wither effect anyways. In that case, you need to make a second script for other players of what could be missing. In my friend's case, he gets the wither effect when he is hit with the sword, and he can't see the sword. So all that's left is to add the sword on his end. The host/client of the LAN world would use the top script, while all other players would use the following script:

<code>ModPE.setItem(700, "withersword", 0, "Wither Sword", 1);</code>

Like, that is it. Consider that the host is the client and one can say there "already is a multiplayer compatibility". All that's left is to add the basics into the other player's game. Now that the second player sees the sword, and is able to use it, you have made a successful(?) multiplayer ModPE thing. Correct me if i'm wrong.

**Comment by KairusDarkSeeker** [comment]
that's working, but they can't use it when the other one doesn't have the script
## for example I have the mod script the joined my sister's world and its not working and it seems she is dead but not
## and when my sister uses the rideAnimals mod script its working fine (on mcpe 0.11.0)
