### ISSUE TITLE
.

### ISSUE THREAD

**Issue by officialmcpro32** [zhuowei/MCPELauncher#410]
@zhuowei is it possible?

**Comment by jose-vm** [comment]
This is not an issue of BlockLauncher. Please close this issue.

**Comment by Black-DeathPE** [comment]
No, don't ask Zhuowei to do this. He works on Android, and has no interest to update ModPE. He's happy for other people to. Close this issue, please.

**Comment by sliceofcode** [comment]
Zhuowei doesn't have a Mac, so he can't make one.

**Comment by jose-vm** [comment]
@sliceofcode treebl's dead, lol
he wouldn't work on modpe ios again
