### ISSUE TITLE
We need 0.13.1 support!!

### ISSUE THREAD

**Issue by QuintonMostert** [zhuowei/MCPELauncher#411]
Please fix blocklauncher for 0.13.1 it can only launch in safe mode !
Dont forget to fix the modpe.levelselect also cuzz it was broken in 0.13.0 and the ride entity function too.

Thanks @zhuowei

**Comment by officialmcpro32** [comment]
Well it works for me 0.13.1

**Comment by Black-DeathPE** [comment]
Works for me - disable your texture pack.

**Comment by QuintonMostert** [comment]
Mods support dude

**Comment by officialmcpro32** [comment]
@QuintonMostert it is supported
