### ISSUE TITLE
pls help me.. howto fix this

### ISSUE THREAD

**Issue by Randell24** [zhuowei/MCPELauncher#415]
![screenshot_2015-12-17-07-04-17](https://cloud.githubusercontent.com/assets/16328531/11856835/85aefb9c-a48e-11e5-8fea-106ecfef02fb.png)

**Comment by jose-vm** [comment]
The creator hasn't updated it for 0.13. Please be patient so he can update it.

Besides, this isn't a BL issue, so please close it.
