### ISSUE TITLE
MODS do not take NO ZENFONE 2!

### ISSUE THREAD

**Issue by ArcherFx** [zhuowei/MCPELauncher#416]
hello, I am reporting this bug on behalf of everyone who has a zenfone and are unable to play with mods, every time I install and active a mod, the block launcher does he not get inside the world (disables it), and most people who have this phone model, say it's because of him that is a processor INTEL ATOM Z3580 CPU 2.33 GHz, and we'd like you would offer a support to ele.I hope you read this!, already bound
![screenshot_2015-12-17-16-18-16](https://cloud.githubusercontent.com/assets/16339847/11878009/22074918-a4da-11e5-8ed4-4359f212ea72.jpg)
![screenshot_2015-12-17-16-18-36](https://cloud.githubusercontent.com/assets/16339847/11878012/220da27c-a4da-11e5-8e25-c6c61fe63217.jpg)
![screenshot_2015-12-17-16-19-18](https://cloud.githubusercontent.com/assets/16339847/11878013/221ce4b2-a4da-11e5-9de6-ecc9d63f0b1e.jpg)
![screenshot_2015-12-17-16-19-46](https://cloud.githubusercontent.com/assets/16339847/11878011/220afaf4-a4da-11e5-8bbc-174731de6f36.jpg)

**Comment by Black-DeathPE** [comment]
BlockLauncher mods do not work on x86 processor devices.

**Comment by ArcherFx** [comment]
but the developer can not add support?

**Comment by zhuowei** [comment]
Please see #284: the latest beta has some support

**Comment by zhuowei** [comment]
Atom support is being worked on: please try the latest beta
