### ISSUE TITLE
function entityAddedHook not working in entityid 63

### ISSUE THREAD

**Issue by FengYue1999** [zhuowei/MCPELauncher#417]
entityAddedHook is not working in version1.11.1 block launcher, not working in entity id 63.
if your friends enter your game.  the function is not activating.
sorry im not good in english,im from china

**Comment by jose-vm** [comment]
Players in multiplayer have different entity ids rather than 63. Please delete this issue.

**Comment by FengYue1999** [comment]
you wrong.

you can try this.
var c=0
function entityAddedHook(entity){
if(Entity.getEntityTypeId(entity)==63){
c++
clientMessage("you are player "+c)
}
}

**Comment by FengYue1999** [comment]
why 1.10.4 version of blocklauncher is working on mcpe 0.12.x?
why 1.11.1 version of blocklauncher is not working on mcpe 0.13.x

**Comment by FengYue1999** [comment]
@jose-vm 
@zhuowei please fix this!

**Comment by DarkTornado** [comment]
If you use this ModPE Script, entityAddedHook will be fixed. (includd other scripts)
When entityAddedHook is called, Blocklauncher cannot check if a new entity is player or not.
But after a moment it can check. This script calls entityAddedHook again after a moment.

function entityAddedHook(e) {
    if (Entity.getEntityTypeId(e) == 0) {
        new java.lang.Thread({
            run: function() {
                java.lang.Thread.sleep(150);
                if (Player.isPlayer(e)) net.zhuoweizhang.mcpelauncher.ScriptManager.callScriptMethod("entityAddedHook", e);
            }
        }).start();
    }
}

**Comment by zhuowei** [comment]
Fixed in latest beta.
