### ISSUE TITLE
ModPkg Files not working

### ISSUE THREAD

**Issue by Akharote1** [zhuowei/MCPELauncher#422]
Recently, I found out about block launcher's support for .modpkg files which can allow mods with multiple files and a metadata.json to specify the information about the author. I decided to give it a try today. However when importing it, it gives me a error (Shown in attached image). I would love to see support for these new file formats. So I would request @zhuowei to fix it
![screenshot_2015-12-19-15-52-19](https://cloud.githubusercontent.com/assets/8598217/11912576/b8db14c0-a668-11e5-9a7c-fa729e57819d.png)

**Comment by KairusDarkSeeker** [comment]
Yup i had this bug too

**Comment by sliceofcode** [comment]
Eheh. I forgot how you were supposed to import them. Help @zhuowei?

**Comment by KairusDarkSeeker** [comment]
So thats why when i test xcripter0 it shows the same message too

**Comment by zhuowei** [comment]
It's no longer supported.

**Comment by KairusDarkSeeker** [comment]
fk!!!!!
