### ISSUE TITLE
Entity hit block hook

### ISSUE THREAD

**Issue by ScriptGenius** [zhuowei/MCPELauncher#430]
I want to create PaintBall mod. How I can get snowball position when it will collision with wool block???

**Comment by sliceofcode** [comment]
Sorry, this isn't the place to ask those kinds of questions. This issue tracker is for reporting problems with BlockLauncher.

**Comment by ScriptGenius** [comment]
ok thx sorry

**Comment by KairusDarkSeeker** [comment]
yeah this is a great idea

**Comment by Black-DeathPE** [comment]
would definitely be awesome - then i could make arrows be removed once they land

**Comment by zhuowei** [comment]
for snowballs, eggs, and experience bottles, I added projectileHitBlockHook and projectileHitEntityHook.

**Comment by KairusDarkSeeker** [comment]
When is the latest blocklauncher coming @zhuowei?
