### ISSUE TITLE
My mod crashes on 0.13.1 [not 0.13.0 below]

### ISSUE THREAD

**Issue by KairusDarkSeeker** [zhuowei/MCPELauncher#438]
# I've been working for months for my mod to finish but its GUI is only simple, try this mod on MCPE 0.13.1 it'll crash blocklauncher instantly

[Download Mod](https://github.com/zhuowei/MCPELauncher/files/71585/Switch_Mod_Kairus.Dark.Seeker.js.zip)

PS sorry for the zip file just open it using ES File Explorer (not your built-in file manager) and import the mod cuz github is only allowing specific files

**Comment by zhuowei** [comment]
thanks

**Comment by zhuowei** [comment]
It... didn't crash MCPE at all; are you sure it's this mod's fault or is it an addon that crashed?

**Comment by zhuowei** [comment]
Please try with the latest beta: http://zhuoweizhang.net/MCPELauncher/MCPELauncherApp-release-beta.apk

**Comment by KairusDarkSeeker** [comment]
Its the mods fault, cuz its slow at loading.

**Comment by KairusDarkSeeker** [comment]
And are the issues fixed then?

**Comment by zhuowei** [comment]
0.13.1 is now properly supported.
