### ISSUE TITLE
Addons with custom items with ID above 512+ crash

### ISSUE THREAD

**Issue by jose-vm** [zhuowei/MCPELauncher#440]
Holding a custom addon item with extended item id array id in Creative makes the game crash.
This is already known by Zhuowei. I made the issue to be aware by a GitHub notification of it being fixed without having to check Twitter.

**Comment by zhuowei** [comment]
This is probably going to have to wait until 1.11.3

**Comment by jose-vm** [comment]
ok

**Comment by zhuowei** [comment]
Are you sure about the crash? I made an addon with extended ID and it works fine https://github.com/zhuowei/MCPELauncher-addons/tree/master/makeitemexample

**Comment by jose-vm** [comment]
Hmmm

Probably is the Item struct I'm using is the one causing the problem?

**Comment by jose-vm** [comment]
Your example also crashes on my device. Probably that's the error? Nexus 5, Android 4.4.4, latest BL and MCPE 0.13.1

**Comment by zhuowei** [comment]
ok. Nexus 6P, Android 6.0.1, latest BL, MCPE 0.13.1, ModPE scripts are on

**Comment by jose-vm** [comment]
I always have ModPE script support off. Would that influence the behavior of BL?

**Comment by jose-vm** [comment]
Fix: I had ModPE script support off, so I turned it on and the addon worked fine.

**Comment by zhuowei** [comment]
Fixed in the latest beta (the extended item hook for textures is now activated when ModPE is disabled)
