### ISSUE TITLE
My block launcher crashes

### ISSUE THREAD

**Issue by Belvix** [zhuowei/MCPELauncher#443]
My block launcher crashes whenever I load any mod. After re opening, It becomes safe mode.

My device is Dell Venue 7 .this mod loading crash was not there in Minecraft PE 0.8.x. This was after the 1.9 mcpe version.

**Comment by Mrangel17** [comment]
Did you update blocklancher to latest version they realaesed one for Intel Atom devices. Here is the linkhttps://play.google.com/store/apps/details?id=net.zhuoweizhang.mcpelauncher&hl=en&referrer=utm_source%3Dgoogle%26utm_medium%3Dorganic%26utm_term%3Dblock+launcher+google+play&pcampaignid=APPU_1_YMZ-Vu2pA8uAjwOq7omQBQ
