### ISSUE TITLE
add Item.getTexture():

### ISSUE THREAD

**Issue by arkLaze** [zhuowei/MCPELauncher#449]
its a very helpful

**Comment by officialmcpro32** [comment]
Why?

**Comment by zhuowei** [comment]
Does it get the texture name or?

**Comment by officialmcpro32** [comment]
@zhuowei both! But I want that it checks the item's name

**Comment by jose-vm** [comment]
This isn't possible. Doing Item::getIcon returns TextureUVCoordinateSet, the one that doesn't have a name parameter. Unless Zhuowei hooks the setIcon function and manually creates a map with all icon names and ids, but that would be a pain in the ass.

**Comment by zhuowei** [comment]
@officialmcpro32 @arkLaze I added one that only gets the texture position in the terrain-atlas/items-opaque.tga (Item.getTextureCoords()). Hopefully that's good enough: if that's not sufficient, please reopen the issue.

**Comment by officialmcpro32** [comment]
@zhuowei how about creating tile entites in ModPE?, also yes that's enough for me
