### ISSUE TITLE
Missing reposity

### ISSUE THREAD

**Issue by JoJoDeveloping** [zhuowei/MCPELauncher#452]
I cannot clons your MCPELauncher-app reposity for building BlockLauncher (Step 7), because it is not there. Please update your building instructions...

**Comment by RandomAltThingy** [comment]
1. This is OLD source code. It won't run now.
2. Check first. GitHub.com/zhuowei/mcpelauncher-app

**Comment by jose-vm** [comment]
@zhuowei close this issue
