### ISSUE TITLE
Level.destroyBlock damages the tool / weapon that the player have selected

### ISSUE THREAD

**Issue by Insane-96** [zhuowei/MCPELauncher#458]

**Comment by officialmcpro32** [comment]
Uh this is cool it would be useful for making custom tools

**Comment by Insane-96** [comment]
Yeah, but for what I need is really annoying, maybe add an optional paramenter like Level.destroyBlock(int x, int y, int z, bool dropBlock, bool damageTool);

**Comment by officialmcpro32** [comment]
Idk why but the doBlockDrop parameter doesn't work

**Comment by Insane-96** [comment]
Because depends on the tool in the hand

**Comment by RandomAltThingy** [comment]
Of course it damages the tool... You broke a block. Level.destroyBlock() just determines whether to drop the block item after break or not.

**Comment by Insane-96** [comment]
Never happened since 0.13

**Comment by zhuowei** [comment]
Should be fixed in 1.11.4.
