### ISSUE TITLE
Issue with Entity.addEffect()

### ISSUE THREAD

**Issue by DiegoGTRatty** [zhuowei/MCPELauncher#464]
Okay, so some effects apparently broke with the recent updates. The effects in particular being:

MobEffect.movementSpeed
MobEffect.jump

EDIT: I am using the latest non-Pro version on a Moto G Android 5.0 in case there are incompatibility issues, but I hardly believe that's the case.

**Comment by Black-DeathPE** [comment]
movementSpeed works for me, make sure you are using the arguments in the right order.

**Comment by zhuowei** [comment]
Both worked fine for me: I'm using https://github.com/zhuowei/ModPEScripts/blob/master/addeffect.js with the command /effect jump and /effect movementSpeed which calls

```
Entity.addEffect(getPlayerEnt(), MobEffect.movementSpeed, 20*30, 0, false, true);
// and
Entity.addEffect(getPlayerEnt(), MobEffect.jump, 20*30, 0, false, true);
```
