### ISSUE TITLE
Doesnt work for acer iconia one 7??

### ISSUE THREAD

**Issue by Lancego** [zhuowei/MCPELauncher#468]
It keeps saying "Unfortunately the version of Minecraft PE on this device is not compatible with Blocklauncher. Please install Minecraft PE for Intel processors." What does that mean?

**Comment by Lancego** [comment]
Pics:
![screenshot_2016-01-04-16-01-24](https://cloud.githubusercontent.com/assets/13486357/12085598/2d9a9cc0-b309-11e5-9a96-a14b28b2133d.png)
![screenshot_2016-01-04-16-01-39](https://cloud.githubusercontent.com/assets/13486357/12085604/37583614-b309-11e5-8a53-24094c323015.png)

**Comment by zhuowei** [comment]
You need the special Intel version of MCPE (if you're using a pirated version, it's going to be an ARM version; you need to get it from Google Play or ask for someone else with an Intel device such as Zenfone to back up their legit copy)
