### ISSUE TITLE
Bug which will have the most clickbait title, in GitHub issues history

### ISSUE THREAD

**Issue by sero583** [zhuowei/MCPELauncher#471]
A function which will return a string in the clients current selected language.
Like a function ModPE.getStringInClientsLanguage(key); like i want to make See which mob mod it is, if the Mob is pointed for example the pointed entity is a cow, no the user don't understand english at it's best and don't know what mob that is, then we could use the function to return the cow's name for example in the spanish language.
This is important for multilanguage support for mods.

**Comment by sliceofcode** [comment]
```
i18n.LANGUAGE_ENGLISH;
i18n.LANGUAGE_SPANISH;
...

i18n.getLanguage(); // Gets language
i18n.getLocalizedValue(key); // Gets a key, but localized for the current language
i18n.setLocalizedValue(lang, key, value); // Sets a key for a language
```

**Comment by Black-DeathPE** [comment]
"Function which will be the most important thing, in MC:PE modding history" not really at all

**Comment by zhuowei** [comment]
I18n.setLocalizedValue already exists - it's called ModPE.langEdit; the rest I'll add.

**Comment by zhuowei** [comment]
ModPE.getLanguage() and ModPE.getI18n("name") added to latest beta. Thanks!
