### ISSUE TITLE
Add a new function in Block

### ISSUE THREAD

**Issue by KairusDarkSeeker** [zhuowei/MCPELauncher#474]
Im really waiting for you zhuowei to add a Block method named Block.defineLiquidBlock(id, opaque, blah blah); something like that and 'blah blah' change it into any feature like you can drown or u can be burned alive like lava that would be really appreciated @zhuowei and BTW please change the BlockLauncher's user interface theme to LIGHT not DARK

**Comment by Black-DeathPE** [comment]
The way BlockLauncher is would look atrotious with light theme

**Comment by zhuowei** [comment]
Liquid blocks will take up *TWO* block IDs - I'll add it in, but I'm not sure if most mods could find two empty block IDs

**Comment by KairusDarkSeeker** [comment]
Add ' Block.defineChest() ' too

**Comment by KairusDarkSeeker** [comment]
# And why didn't anyone think of this method before?

**Comment by KairusDarkSeeker** [comment]
What is the value of material: water??????

**Comment by jose-vm** [comment]
Close the issue
