### ISSUE TITLE
Annoying Bug

### ISSUE THREAD

**Issue by KairusDarkSeeker** [zhuowei/MCPELauncher#478]
You burn when your on lava but on the original MCPE you can't burn

**Comment by Black-DeathPE** [comment]
no, you burn no matter what, unless you're in creative or have fire resistance.

**Comment by KairusDarkSeeker** [comment]
Lol test it in MCPE 0.13.1 without using BlockLauncher

**Comment by zhuowei** [comment]
I'm assuming you mean Creative. Tested on latest beta: in Creative, Player has flames in the vision, but doesn't take damage. This is the exact same behaviour as regular MCPE 0.13.1.

Mind telling me which gamemode you're in and what you mean by burning (taking damage or just have flames show up)?

**Comment by KairusDarkSeeker** [comment]
It does differ
