### ISSUE TITLE
Can't summon lightning

### ISSUE THREAD

**Issue by Flubberlutsch** [zhuowei/MCPELauncher#479]
When I use Level.spawnMob(x,y,z,93) to summon a lightning, the lightning won't show up until I rejoin the world, so it's kinda paused... Please fix this

**Comment by jose-vm** [comment]
Try with Entity.spawnMob?

**Comment by Flubberlutsch** [comment]
Already did, it doesn't work at all with Entity.spawnMob (the lightning will never appear, not even after rejoining the world)

**Comment by jose-vm** [comment]
Yeah, I am also having this issue. @zhuowei I reproduced it in a Nexus 5 Android 4.4.4

**Comment by zhuowei** [comment]
This is known since #271; I'm not sure why this happens

**Comment by zhuowei** [comment]
Fixed.
