### ISSUE TITLE
New hook

### ISSUE THREAD

**Issue by KenMizz** [zhuowei/MCPELauncher#481]
ModPE.setDrinkItem();
I hope @zhuowei can add it

**Comment by jose-vm** [comment]
That's not a hook suggestion but a function one

**Comment by Black-DeathPE** [comment]
That's basically food item. One of the newer APIs (idk the name) allows you to edit data of an item as if it was the items.json.

**Comment by KenMizz** [comment]
Oh,I make a mistake,sorry

**Comment by zhuowei** [comment]
Yeah, this is possible to do with Item.setProperties

**Comment by jose-vm** [comment]
actually, instead of "use_animation": "eat" it should be "use_animation": "drink" :b
