### ISSUE TITLE
maybe?,ModPE.getDifficulty(); 

### ISSUE THREAD

**Issue by Izaac9236** [zhuowei/MCPELauncher#484]
Options::getDifficulty() const;
Options::setDifficulty(int);

ModPE.getDifficulty();
ModPE.setDifficulty(par1int);

This would be useful on occasion

**Comment by jose-vm** [comment]
nah

**Comment by Izaac9236** [comment]
@jose-vm blah .. more why? Did you block launchrr developer not; -; cry cry more is free joe

**Comment by Izaac9236** [comment]
:new_moon_with_face:

**Comment by Izaac9236** [comment]
:sun_with_face::+1:

**Comment by TrinityDevelopers** [comment]
What's so bad about that Joe?  Seems good to me...

**Comment by jose-vm** [comment]
Zhuowei would need to add a singleton for Options, that takes long sometimes :b

**Comment by MrIrishMiner** [comment]
This would be good for modded adventure maps. Using the redstone update hook and this, it would auto set the difficulty, but I do see where it would take a long time.

**Comment by jose-vm** [comment]
Zhuowei already added this in the latest BlockLauncher update. @zhuowei close this

**Comment by zhuowei** [comment]
@jose-vm Haven't added setDifficulty yet

I'm not sure about setDifficulty: should it only set difficulty for the currently loaded world without moving the difficulty slider (i.e. exiting then reentering world reverts to original difficulty) or actually change the difficulty slider and risk annoying users (who might not notice that a script changed their difficulties option and ruin a world or something)

**Comment by jose-vm** [comment]
@zhuowei I meant ModPE.getDifficulty

**Comment by jose-vm** [comment]
@zhuowei Wait, do level's saved difficulty actually influence the game? Anyway, I would prefer it to change the difficulty slider.

Or why not both?
Level.setDifficulty
ModPE.setGameDifficulty

**Comment by MrIrishMiner** [comment]
That's what I was referring to.

**Comment by zhuowei** [comment]
Levels do not save difficulty afaik; added Level.setDifficulty which doesn't persist.
