### ISSUE TITLE
add Entity.hasPenis(ent,boolean);

### ISSUE THREAD

**Issue by Izaac9236** [zhuowei/MCPELauncher#486]
:v nowww for make sex in minecraft like a real life (͡' ͜ʖ ͡'(͡° ͜ʖ ͡°)

**Comment by Godsoft029** [comment]
Serious?

**Comment by DiegoGTRatty** [comment]
@zhuowei Please close this.

**Comment by sliceofcode** [comment]
@zhuowei @Izaac9236 Are you kidding me? Please close this. We seriously need more people managing this issue tracker, it is very hectic.
