### ISSUE TITLE
Creative Inventory Crash??

### ISSUE THREAD

**Issue by StolenSoul90** [zhuowei/MCPELauncher#489]
Yesterday it worked..today it crashes as soon as I click to go into my creative inventory. Yes, it's a fresh copy of BL just Uninstaller and reinstalled yesterday while cleaning up my phone.

**Comment by zhuowei** [comment]
Try latest beta: on a clean install ModPE scripts are turned off, and this crashes addons

**Comment by StolenSoul90** [comment]
Where can I get latest beta?

**Comment by zhuowei** [comment]
http://tinyw.in/bl

**Comment by StolenSoul90** [comment]
That worked thank u

**Comment by jose-vm** [comment]
close the issue.
