### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by Toganon** [zhuowei/MCPELauncher#493]
function useItem(){
Player.enchant(Player.getSelectedSlotId(), Enchantment.LOOTING, 5);
}

I wrote a mod in this way .When I tap a block , No error appeared , but Nothing happened . Am I wrong? Or bug?

**Comment by DiegoGTRatty** [comment]
I don't think that has been implemented yet.

**Comment by zhuowei** [comment]
What were you holding in your hand? Is it enchantable with looting at level 5?

**Comment by Toganon** [comment]
Oh…I'm sorry. I tried it again,I can do it.

**Comment by Toganon** [comment]
I held seeds.

**Comment by Black-DeathPE** [comment]
Kinda an issue I guess, I think we should be able to enchant items to whatever enchantment we wish :)

**Comment by zhuowei** [comment]
I added a return value to Player.enchant so you can check if the enchant failed:
```
if (Player.enchant(....)) {
clientMessage("yep it enchanted")
}
```

Forcing enchantment will come later (it's changing `false` to `true` in one line of code), but I want to get enchanting api released first
