### ISSUE TITLE
doesnt work for Asus Zenfone 4 !

### ISSUE THREAD

**Issue by masternija** [zhuowei/MCPELauncher#495]
![screenshot_2016-01-15-20-37-52](https://cloud.githubusercontent.com/assets/14352043/12363397/00846afe-bbc9-11e5-952c-e2bff0242106.jpg)

**Comment by zhuowei** [comment]
You're using a pirated version of MCPE, which are all for ARM processors; BlockLauncher needs the Intel version on Intel devices. Buy the legit version of MCPE from Google Play (which gets you the Intel version)

**Comment by MatheusMola** [comment]
Abril

**Comment by MatheusMola** [comment]
Abril

**Comment by THEGAMERPROLOOR** [comment]
Buena

**Comment by optimus12** [comment]
acabo de descargar louncher y cuando me meto me manda a esta pagina por que

**Comment by yassin10** [comment]
Bitte funksuniere

**Comment by jajajajajj** [comment]
Minecraft siiiiii

**Comment by FraanzMasterProo** [comment]
No meda lo abro y me trae a esta pagina

**Comment by jdjdjjd** [comment]
Abril

**Comment by Thinknoodles** [comment]
I have MCPE 0.14.0 bd 3 its still 0.14.0 what's the matter with that blocklauncher

**Comment by samuel1432** [comment]
Hola como funciona esto??

**Comment by server728** [comment]
No mms no sirve

**Comment by joemckellar20** [comment]
Do from download it from Amazon appstore

**Comment by lucasnsouza3** [comment]
Como que funciona  como que funciona o que é classe A pessoa

**Comment by lucasnsouza3** [comment]
Como que funciona o Block Launcher pessoal

**Comment by f3rnand0gansito** [comment]
Como funsiona

**Comment by butterflix** [comment]
No funciona

**Comment by butterflix** [comment]
??no

**Comment by dougie123** [comment]
I smoothie. block launcher

**Comment by ck28785** [comment]
Good

**Comment by afnan45** [comment]
What version it want?

**Comment by ck28785** [comment]
0.14.0

**Comment by afnan45** [comment]
0.14.0 b6,isn't?

**Comment by ck28785** [comment]
0.14.0 b4

**Comment by aksoy50** [comment]
Evet

**Comment by Phferrari** [comment]
Como que faz isso?

**Comment by iclojano15** [comment]
Don't have money

**Comment by trimerigeko78** [comment]
No funciona como le ago

**Comment by wh2004** [comment]
hello

**Comment by PocketKiller** [comment]
Spammers...

**Comment by yoshikirby43** [comment]
0.14.0 has been just came out may you add mod script support again

**Comment by animeci** [comment]
-.-

**Comment by AwesomeTeenBoy** [comment]
Why does work for my tablet?

**Comment by opole** [comment]
Gdjaouh

**Comment by kalipsom** [comment]
Meu cu

**Comment by tphong020** [comment]
????

**Comment by ArturGamer324** [comment]
Minecraft 0.14.0
Por 
Favor me ayudan
Siiiii

**Comment by enes4238** [comment]
Selam

**Comment by eddiegarci** [comment]
No funciona por k cada k abrimos minecraft launcher  nos manda a esta pagina ojala lo arreglen y nos mande luego luego al juego no a esta pagina

**Comment by Asgro** [comment]
....

**Comment by chanomix** [comment]
No funciona

**Comment by GabrieelGomes** [comment]
Block launcher

**Comment by KBreezy** [comment]
I have a Intel version but it still doesn't work

**Comment by kaow2548kaow** [comment]
ก

**Comment by ditilifi** [comment]
Come on why is not working tell me why is not working in Minecraft or 0.14.0

**Comment by Mathisc59** [comment]
Génital

**Comment by Mathisc59** [comment]
Genial

**Comment by sonerobak** [comment]
Çözüm ne

**Comment by jssjns** [comment]
Ggggggg

**Comment by 22ufydydhdg** [comment]
Hhbhvhchfhfhfhvhvhguhugububub

**Comment by TheGames126** [comment]
I'm sure it will have an update I can't live without hacks 😯

**Comment by jason901124** [comment]
要怎能裝模組，還是這只能聊天？

**Comment by jason901124** [comment]
怎麼

**Comment by Dmitryrusnak** [comment]
У меня не работает blocklauncher
