### ISSUE TITLE
Recipes do not take damage into account

### ISSUE THREAD

**Issue by zhuowei** [zhuowei/MCPELauncher#496]
```Item.addCraftRecipe(1, 1, 0, [5, 1, 4])``` crafts stone with oak wood instead of jungle wood as stated in the recipe. https://twitter.com/vcraft7/status/688132378691174401

**Comment by TheViictor** [comment]
Well, I hope that you fix this as soon as possible

**Comment by zhuowei** [comment]
Finally fixed in the new beta. Phew.
