### ISSUE TITLE
Item.getName() bug

### ISSUE THREAD

**Issue by officialmcpro32** [zhuowei/MCPELauncher#504]
I used Entity.setNameTag(pig,Item.getName()); it returns null

**Comment by zhuowei** [comment]
How are you calling it? Item.getName takes three parameters: (id, damage, raw)
so call it like
Item.getName(5 /* planks */, 0, false)

**Comment by officialmcpro32** [comment]
I used it with an attackHook() to make a name tag mod it checks the items name then sets the name tag

**Comment by zhuowei** [comment]
Can I see the exact code?

**Comment by officialmcpro32** [comment]
function attackHook(attacker,victim){

Entity.setNameTag(victim,Item.getName());

}

**Comment by officialmcpro32** [comment]
There

**Comment by zhuowei** [comment]
Try
```
Entity.setNameTag(victim, Item.getName(Entity.getCarriedItem(attacker)))
```
and see if that works?

**Comment by officialmcpro32** [comment]
Ok
