### ISSUE TITLE
BL Hook: startDestroyBlock won't work

### ISSUE THREAD

**Issue by SaloEater** [zhuowei/MCPELauncher#509]
Looks like this hook: function startDestroyBlock(x,y,z,side){} won't work.
Even simple as this:
function startDestroyBlock(x, y, z, side){
clientMessage("Start Destroy Hook works");
} 
doesn't work. 
Where is the problem?

**Comment by Sin0psysS** [comment]
Yup see [this](https://github.com/zhuowei/MCPELauncher/issues/487),
it simply seems to bug for the last two versions of bl

**Comment by SaloEater** [comment]
Will try downgrade bl. Thanks.
