### ISSUE TITLE
projectileHitEntityHook doesn't work.

### ISSUE THREAD

**Issue by Yroki12** [zhuowei/MCPELauncher#510]
function projectileHitEntityHook(projectile,targetEntity){
clientMessage(projectile+'/'+targetEntity);
	if(Entity.getEntityTypeId(projectile)==81){
		Entity.setHealth(targetEntity,Entity.getHealth(targetEntity)-2);
		}
}

If I different, I want to know how to use this function.

**Comment by Black-DeathPE** [comment]
Had this issue too. Target entity is incorrect.

**Comment by zhuowei** [comment]
OH WOW THIS HAS GOT TO BE THE DUMBEST MISTAKE I EVER MADE WOW HOLEY LOL
Yeah, I forgot to call the method to get the entity ID in the code, so instead of the entity ID the function got the memory address of the entity instead.

I win the fail of the year award.

The fix will be in the next beta.
