### ISSUE TITLE
Enhancement: Add a function to set an armor's texture

### ISSUE THREAD

**Issue by jose-vm** [zhuowei/MCPELauncher#515]
My suggestion is to add a function to BL to set an armor's texture using bl_armorRenders, example:
bl_setArmorTexture(int, mce::TexturePtr*)

For me, making a dlsym of a symbol in an addin is easier than using an array that will later crash

**Comment by jose-vm** [comment]
You would probably watto know why I'm so desesperate for this, and I don't blame you, lol
I'm making an addon that is supposed to add more weapons to the game, including armor

**Comment by jose-vm** [comment]
Can you please work on this now? ^^

**Comment by zhuowei** [comment]
yes

**Comment by zhuowei** [comment]
@jose-vm Added - thank you for the suggestion! Example addon is at https://github.com/zhuowei/MCPELauncher-addons/commit/9bd9bac5d7d1f4abe97f3b28779b30e696d2923a; beta at http://tinyw.in/bl

**Comment by jose-vm** [comment]
this crashes as hell lol
