### ISSUE TITLE
Every texture pack crashes

### ISSUE THREAD

**Issue by zhuowei** [zhuowei/MCPELauncher#516]
https://twitter.com/geraldjames15/status/690028924710043648

**Comment by GeraldJames15** [comment]
![screenshot_2016-01-21-19-39-54](https://cloud.githubusercontent.com/assets/16817474/12479686/d2709080-c077-11e5-921a-2cbb206e7f3e.png)


Thats The Bug Report! Pls it always happens 😭😭😭😭 whenever i insert any of my downloaded texture packs! Help me fix this!

**Comment by GeraldJames15** [comment]
Ok...so i look again whats the version of the texture pack that im using...i was expecting that im using 0.12. But when i saw "0.13.0+",i freak out! Its the blocklauncher! SO I REALLY NEED HELP TO FIX THIS BUG! 😭 😢

**Comment by sliceofcode** [comment]
Texture packs work for me...

**Comment by GeraldJames15** [comment]
But...i don't work properly for me 😢

**Comment by GeraldJames15** [comment]
I meant *it not i

**Comment by zhuowei** [comment]
@GeraldJames15 Can you export a bugreport from your device by following https://www.youtube.com/watch?v=YxQ3NTloD2c?

**Comment by GeraldJames15** [comment]
I did

**Comment by GeraldJames15** [comment]
![screenshot_2016-01-21-19-39-54](https://cloud.githubusercontent.com/assets/16817474/12511493/a665e848-c14c-11e5-9f88-17d5004170a7.png)

See?

**Comment by zhuowei** [comment]
* Watch the video
* Go to Settings -> Developer Options -> Take Bug Report
* Tap it
* Send it to Google Drive or Dropbox
* put the link here

**Comment by zhuowei** [comment]
Closing because of a lack of information. :(
