### ISSUE TITLE
the new .modpkg doesn't work [bug]

### ISSUE THREAD

**Issue by officialmcpro32** [zhuowei/MCPELauncher#525]
@zhuowei the new format doesn't load the script it does nothing but the example you gave works idk why I tried it on redstone + it doesn't work I zipped the file then renamed to r+.modpkg also check your twitter many people were also having problems with it.

**Comment by zhuowei** [comment]
thanks. can I get a link to the modpkg? also redownload the beta?

**Comment by Black-DeathPE** [comment]
For me it loads textures but not the script.

**Comment by officialmcpro32** [comment]
@zhuowei I did redownload it and here's my mod http://www.mediafire.com/download/odgd5vonbb31ten/Redstone_%2B.modpkg

**Comment by Khristian-kun** [comment]
@officialmcpro32 your error is that you have to put the files in the modpkg, not making a folder and then add everything, and second, why do you have to add a map in the mdpkg? thats weird!

**Comment by Khristian-kun** [comment]
@officialmcpro32 @zhuowei isnt a bug, i fixed him modpkg, https://www.dropbox.com/s/hztf6qfdum1k34t/RedstonePlus.modpkg?dl=0

**Comment by officialmcpro32** [comment]
@Khristian-kun the texture doesn't load it says failed to import missing blah blah, but I have the texture

**Comment by Khristian-kun** [comment]
so make a try, then add the functions that defined the item/blocks with the mod textures, and then do a catch error defining the items/blocks using vanilla textures, it will load with the vanilla textures, but reload BL and it will load the mod textures

**Comment by zhuowei** [comment]
Also why does the modpkg have a terrain.meta in it; I'm going to be filtering those out (you shouldn't mess with terrain.meta directly; just use the terrain-atlas/ folder thing)

**Comment by officialmcpro32** [comment]
@zhuowei ignore those I just copied the folder but I found ht real bug custom textures with custom names on the doesn't work
