### ISSUE TITLE
Add Apk Texture packs features

### ISSUE THREAD

**Issue by GoneTone** [zhuowei/MCPELauncher#526]
You can write a BlockLauncher use Apk Texture packs features?
And the same Apk Mod.

**Comment by officialmcpro32** [comment]
What do you mean by that?

**Comment by officialmcpro32** [comment]
Both apk and normal texture packs has them same features if that's what you meant.

**Comment by GoneTone** [comment]
Texture packs is made into Apk, installation can be directly imported.

**Comment by officialmcpro32** [comment]
What? Texture packs are not apk the are zip

**Comment by GoneTone** [comment]
Apk allowing users update more convenient

**Comment by officialmcpro32** [comment]
Wut? It's pointless to make an apk texture pack

**Comment by officialmcpro32** [comment]
@zhuowei please close this issue

**Comment by GoneTone** [comment]
ok....

**Comment by jose-vm** [comment]
@officialmcpro32 He refers to what addons do. Importing textures in the "assets" folder in an addon could do this easily.

**Comment by officialmcpro32** [comment]
Custom textures? Well he can just put the texture in the addon lel

**Comment by zhuowei** [comment]
As @jose-vm pointed out, this kinda works: just add them to the assets/ folder of an addon (it needs the ADDON permission and one .so file, but the so file doesn't have to do anything)

If you need this I can make it such that addons with no code would be loaded for their textures only. That should then satisfy your requirements unless you're selling a paid texture pack (which I've never seen happen)

**Comment by zhuowei** [comment]
Fixed: textures will be loaded from codeless addons. So basically just put
```
    <uses-permission android:name="net.zhuoweizhang.mcpelauncher.ADDON"/>
    <meta-data android:name="net.zhuoweizhang.mcpelauncher.api.targetmcpeversion" android:value="0.13.1"/>
```
in APK manifest and put textures in assets/

**Comment by GoneTone** [comment]
This way I tried, but he will not appear in the BlockLauncher, and no way to fully achieve the degree of texture pack can do.

Sorry, my English is very poor.
