### ISSUE TITLE
Hchhxhxhd

### ISSUE THREAD

**Issue by Lloyd2006** [zhuowei/MCPELauncher#527]
Hhhh

**Comment by Black-DeathPE** [comment]
Very interesting. I think this needs some serious fixing Zhuowei!

**Comment by officialmcpro32** [comment]
@Black-DeathPE that guy needs some serious fixing zhuowe! We need a doctor here lol.

**Comment by officialmcpro32** [comment]
@Lloyd2006 only post bug reports and suggestions here pls don't spam the issue trakcer

**Comment by zhuowei** [comment]
@Lloyd2006 Please describe your issue so that I can help you.
