### ISSUE TITLE
Level.destroyBlock(false); doesn't work

### ISSUE THREAD

**Issue by TheViictor** [zhuowei/MCPELauncher#535]
Well, just try this:
function destroyBlock(x,y,z,blockId,itemId){
var blockId = Level.getTile(x,y,z);
if(blockId==1){
Level.destroyBlock(false);
clientMessage(":v);
}
}

**Comment by zhuowei** [comment]
You're... trying to destroy a block while destroying a block? Destroyception?

**Comment by TheViictor** [comment]
function destroyBlock(x,y,z,blockId,itemId){
if(blockId==1){
Level.destroyBlock(false);
clientMessage(":v);
}
}

It's just that with destroyBlock(false) in the code still drops it

**Comment by zhuowei** [comment]
thanks - will fix.

**Comment by zhuowei** [comment]
Fixed in latest beta.
