### ISSUE TITLE
bl_setArmorTextures crashes upon use

### ISSUE THREAD

**Issue by josevazqm** [zhuowei/MCPELauncher#538]
The title says it all. Tried your example and it also crashes.

**Comment by zhuowei** [comment]
Crash log please?

Also, MFW I get this bug report for the 3rd time
<img src="http://i.imgur.com/uPdqQpH.png">

**Comment by jose-vm** [comment]
BL crashlog or CatLog?

**Comment by zhuowei** [comment]
Never mind, found the issue. Yes, it needs ModPE scripts enabled to work.

**Comment by jose-vm** [comment]
oh, ill try now

**Comment by zhuowei** [comment]
@jose-vm I can make this work with ModPE scripts turned off if you need it. If you don't need it, just close the issue.

**Comment by InusualZ** [comment]
@zhuowei Why you don't make things that could work alongside addons work by default?

PD: Did I express myself well?

**Comment by jose-vm** [comment]
It works, but you need to have ModPE script enabled :b

**Comment by jose-vm** [comment]
Should I close it?

**Comment by zhuowei** [comment]
@InusualZ I do this for a few important things (extended item IDs, initializing Substrate), but I never test with scripts disabled, so a lot of the time I don't even know that stuff stops working with scripts disabled

**Comment by jose-vm** [comment]
@zhuowei Yep, keep it
Also, make it useable without ModPE script support please
