### ISSUE TITLE
hh

### ISSUE THREAD

**Issue by Nezarxxxx** [zhuowei/MCPELauncher#548]
hhh

**Comment by Nezarxxxx** [comment]
woow

**Comment by zhuowei** [comment]
what's the issue, which version of mcpe?

**Comment by InusualZ** [comment]
Zhuowei, no offence but you should ban these guys...

**Comment by zhuowei** [comment]
@InusualZ Github's interface is confusing, and most users do not have English as their first language, so I'm willing to give benefit of the doubt.
