### ISSUE TITLE
Crash with items-opaque folder

### ISSUE THREAD

**Issue by DarkFlames2003R** [zhuowei/MCPELauncher#577]
I have added a file called chorus_fruit_0.png on assets/images/items-opaque on my addon, but when I use setIcon("chorus_fruit", 0); crashes BlockLauncher when I try to see the item.

Android: 4.4.2 and 5.0.2.
Processors: x86 and ARMv7
BL Version: latest Pro version from Google Play
MCPE Version: 0.14.0.b3

(Sorry by bad english, I'm brazilian!)

**Comment by Rattlehead117** [comment]
0.14 dont support mods

**Comment by DarkFlames2003R** [comment]
Yes, it supports mods, but only add-ons, no ModPE Scripts.

**Comment by Rattlehead117** [comment]
Oh :v

**Comment by Rattlehead117** [comment]
That's true

**Comment by Izaac9236** [comment]
Why do you man? :new_moon_with_face:

**Comment by Izaac9236** [comment]
- []
-[  

> `@]gg`

**Comment by zhuowei** [comment]
BlockLauncher for 0.14.0 doesn't support custom textures in packs at all right now (since the items.meta format is slightly different). Please reopen this when full version of 0.14.0 is released.
