### ISSUE TITLE
Can't cast functions | GUI Code

### ISSUE THREAD

**Issue by sero583** [zhuowei/MCPELauncher#579]
At first the only way where you can view important messages, is opening a issue, because everyone is spamming you @ Twitter.
So, my problem is that i can't cast functions and it's important for some GUI Code for me.
I think you know casting.
Button btn = (Button) findViewById(R.id.btn);
The '(Button)' is the cast and if you cast a function, the error says that a ';' isn't there where it should be, but the error just says that because casting isn't implented.
Could you please add it

**Comment by Godsoft029** [comment]
Ummm its JavaSCRIPT not Java

**Comment by Black-DeathPE** [comment]
That code is in Java, so Zhuowei can't really add it, as he didn't code the JavaScript parser ModPE uses. You might be able to find a way to cast functions in JS.

**Comment by sero583** [comment]
Realy dudes im not stupid @Black-DeathPE @Godsoft029, i mean the GUI functions, i need to cast some of them!
Put your stupid comments anywhere you wan't but not here!

**Comment by Black-DeathPE** [comment]
I said a perfectly fine comment. If you're going to snap at me because I *stated* that the thing you're requesting might be possible already, you need to grow up.

**Comment by sero583** [comment]
@Black-DeathPE It's not working!
And if you know a method to cast something, then tell it instead writing your stupid comments like "It's already working".
I think youre 12-13 years old and say you need to grow up

**Comment by Godsoft029** [comment]
You don't need to cast in JavaScript

**Comment by sero583** [comment]
@Godsoft029 Please stop spamming me with your comments you don't need to cast in JavaScript, are your behind brain won't get it?
I need it for GUI Code, but you guys seem like noobs.
Please stop with that spam:
1. Nobody asked you guys
2. You guys spam
3. Your comments are useless
Just stop.

**Comment by Black-DeathPE** [comment]
I don't see how saying that how this suggestion would be hard to add is "useless." However, I've been put off by your immaturity, so I'll stop talking to you now.

**Comment by Black-DeathPE** [comment]
Oh yeah also, don't call me a noob. You have no evidence. If you went and saw what mods I've made you'd not believe that.

Google "ZOMWar mcpe mod," look at the code and then tell me that I'm a noob. Then you'd definitely be making false accusations.

Don't call me a spammer when you see people on this issue tracker making issues with no content or purpose.

**Comment by sero583** [comment]
I don't care in your skills or mods.
You are piss me off, really go seek another one to do.
You mean, youre not a noob, so why you call casting functions useless, only a noob would say that.
Come on go away and i never knew that Elvin ever worked with a guy like you.

**Comment by sero583** [comment]
And please tell me how you would force to soft keyboard to open, if you aren't able to cast something.

**Comment by Godsoft029** [comment]
Android:
InputMethodManager imm = (InputMethodManager) getSystemService(Context.INPUT_METHOD_SERVICE);
imm.showSoftInput(getWindow().getDecorView(), InputMethodManager.SHOW_FORCED);

**Comment by Black-DeathPE** [comment]
That's awkward since this works: `getWindow().setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_STATE_VISIBLE);`
No casting needed.

**Comment by Black-DeathPE** [comment]
And also nobody works with me, I work solo :)

**Comment by sero583** [comment]
Well, @Black-DeathPE you've made it, well im sorry, but for some things casting is needed.
Well im closing this issue
