### ISSUE TITLE
No me esta cojiendo el Block Launcher

### ISSUE THREAD

**Issue by Toxelgamer** [zhuowei/MCPELauncher#614]

**Comment by zhuowei** [comment]
@Toxelgamer Does this still happen in the latest version of BlockLauncher? Which mods and which device are you using?

**Comment by Toxelgamer** [comment]
The device is a Acer Iconia 7 and am using the latest vercion of Blocklauncherpro, even without modifications before crasheaba and now it says my device is not supported

**Comment by zhuowei** [comment]
@Toxelgamer Did you get MCPE from Google Play? You have an Intel Atom processor, which needs a special version of MCPE to work with BlockLauncher. Please buy MCPE from Google Play (the pirated APKs are for regular phones and won't work)
