### ISSUE TITLE
Error on x86 devices

### ISSUE THREAD

**Issue by DarkFlames2003R** [zhuowei/MCPELauncher#633]
When I open BlockLauncher Beta (last beta) appears an error message saying that I need MCPE from Google Play to download ARM MCPE version.

BlockLauncher Version: Last beta
MCPE Version: 0.14.0 build 7
Device: DL Tablet 3405 and Zenfone 5
Android: 4.4.2 and 5.0.1

Ps: I have MCPE from Google Play

**Comment by Rodrigo294X** [comment]
confimed!! pls fix it!

**Comment by zhuowei** [comment]
@DarkFlames2003R @Rodrigo294X Try latest beta (beta 3) which should support x86.
