### ISSUE TITLE
Attack function

### ISSUE THREAD

**Issue by MooGaming227** [zhuowei/MCPELauncher#634]
Would it be possible to specify a mob that can be naturally aggressive (a pigzombie) to attack a spider or a zombie? Probably in Entityaddedhook(cant think of that name). Like:

function entityaddedhook(){

if entity added id = pigzombie{

check for spider

if findmob(Spider) = true{  //this part could be optional if you added the attack function auto after finding the mob

 Attack entity(spider)

Would it be possible?

**Comment by Black-DeathPE** [comment]
Entity.setAggressiveTo(entity, target);
This could be really useful, so I could make any wolves spawn target the player and such. However, entities like wolves will attack an entire entity type, so maybe there could be another function that allows us to make them attack an entity ID.

**Comment by MooGaming227** [comment]
There are ways online but they are always lag.

**Comment by zhuowei** [comment]
Added in latest beta: Entity.setTarget(entity, target).
