### ISSUE TITLE
BL Scripts Crash (0.14)

### ISSUE THREAD

**Issue by officialmcpro32** [zhuowei/MCPELauncher#636]
The new BL crash when I enable scripts

**Comment by Black-DeathPE** [comment]
My mod doesn't work either on it, I'm trying to find the culprit function, but no luck so far.

It crashes on world launch and just force closes. I turned the crash log on, it saves them but they are empty.

**Comment by officialmcpro32** [comment]
@Black-DeathPE @zhuowei for me it does that when u activate ModPE Scripts

**Comment by Black-DeathPE** [comment]
@officialmcpro32 @zhuowei It must be function that you run straight away and I run on new level

**Comment by zhuowei** [comment]
@officialmcpro32 Try again with the latest beta: it fixes at least two crashes at startup

**Comment by Black-DeathPE** [comment]
As for me, it stopped crashing when 0.14.0 full update released

**Comment by officialmcpro32** [comment]
@zhuowei close this issue it works fine now
