### ISSUE TITLE
HERE IS A UPDATE OF "VALUES-ES" (BLOCKLAUNCHER FREE OR PRO 1.11.4+)

### ISSUE THREAD

**Issue by ChargerMc** [zhuowei/MCPELauncher#637]
Here is a update of "Values-es" (Blocklauncher Free or PRO 1.11.4+)
Hello! Sorry to be away so long, here's a clean and newly updated Spanish version of your app. Keep it up.

Link: http://www.mediafire.com/download/wn7q5ll3eopyx75/values-es.zip

Regards

PD: Works on beta too, i think...

**Comment by zhuowei** [comment]
Thank you so much! Will merge for 1.12.1.

**Comment by ChargerMc** [comment]
Oh, your welcome! thanks, its much work kamcord strings!
Can you please send me the new string for Desktop UI? for translate too.

**Comment by zhuowei** [comment]
```
    <string name="pref_zz_desktop_gui">Use Desktop GUI</string>
    <string name="pref_zz_desktop_gui_summary">Change inventory and crafting windows to Desktop mode</string>
```
Thank you so much for your help.

**Comment by ChargerMc** [comment]
`<string name="pref_zz_desktop_gui">Usar GUI de Escritorio</string>
    <string name="pref_zz_desktop_gui_summary">Cambia el inventario y la ventana de crafteo al modo de Escritorio</string>`

Your welcome!
