### ISSUE TITLE
求大神帮忙 这个mcpe的库怎么用，我看首页Building的第7部要下一个BlockLauncher-app，可是网址不能打开

### ISSUE THREAD

**Issue by ljqloveyou123** [zhuowei/MCPELauncher#640]
求大神们帮忙，这个mcpe的库怎么用，我看首页Building的第7部要下一个BlockLauncher-app，可是网址不能打开，万分感谢

**Comment by zhuowei** [comment]
@ljqloveyou123 The source code is no longer available for building: if you need a prebuilt APK, use http://tinyw.in/bl.
