### ISSUE TITLE
New hook

### ISSUE THREAD

**Issue by KenMizz** [zhuowei/MCPELauncher#641]
Block.defineChest();
Item.setItemType();//like Pickaxe,sword..etc
ModPE.isOpenInventory();/
@zhuowei 
:)plz

**Comment by sero583** [comment]
Block.defineChest should look so:
Block.defineChest(amountofchestslots);
What do you mean @KenMizz

**Comment by KenMizz** [comment]
@sero583 it is

**Comment by KenMizz** [comment]
@zhuowei
