### ISSUE TITLE
Please tell me more......(About redstoneUpdateHook)

### ISSUE THREAD

**Issue by GenbuHase** [zhuowei/MCPELauncher#644]
I'm Japanese.
If I couldn't tell you well, I'm sorry.

Please tell me about redstoneUpdateHook!

We couldn't understand about it well in the Google+ Community...

**Comment by zhuowei** [comment]
`function redstoneUpdateHook(x, y, z, newCurrent, worldLoading, blockId, blockDamage)`
x, y, z: position of the block that is receiving the new redstone current
blockId, blockDamage: ID and damage of the block that is receiving the current
newCurrent: the new redstone current, a number from 0 (no current) to 15 (full current)
worldLoading: this is set when the world is loading, as each block receives a redstone update to the current stored in the world: use this if, for example, you have a block that makes a sound when the current changes, and you don't want it to make a sound when the block is first loaded

See https://raw.githubusercontent.com/zhuowei/ModPEScripts/master/piston.js for more information.

**Comment by GenbuHase** [comment]
Thanks!
I'll close this issue:D
