### ISSUE TITLE
startDestrohBlock still wont work. 

### ISSUE THREAD

**Issue by SaloEater** [zhuowei/MCPELauncher#650]
function startDestroyBlock(x,y,z,s){
   clientMessage("Work");
}

This piece of code didn't work. bl feature or my mistake?

**Comment by sero583** [comment]
I too don't know how this is working.

**Comment by sero583** [comment]
I've tryed a very very same code but nothing happens if i start to destroy the block. :/

**Comment by zhuowei** [comment]
I kludged together a stupid solution with the new continueDestroyBlock hook (called every time the player's arm swings to destroy a block) - doesn't work for bedrock and other indestructable blocks yet; will fix.
