### ISSUE TITLE
Entity.rideAnimal(attacker,victim); seems to be broken again.

### ISSUE THREAD

**Issue by TDS200** [zhuowei/MCPELauncher#652]
Like the title says I cannot get "Entity.rideAnimal(attacker,victim);" to work anymore.  It is one of the most important methods in my mod.  I hope it will be fixed soon. :-).

I've tried using it in this simple test code.

```
function attackHook(attacker,victim){
 Entity.rideAnimal(attacker,victim);
}
```
I've also tried replacing "attacker" with "Player.getEntity();" and it still doesn't work.

**Comment by zhuowei** [comment]
in vanilla MCPE you can only ride minecarts and boats, and I didn't disable the code that prevents riding other entities because I wanted to get a release out quickly.

**Comment by zhuowei** [comment]
Fixed.

**Comment by TDS200** [comment]
Thanks, I hope we can use custom models on boats and minecarts soon.
