### ISSUE TITLE
modpkg does not accept items-opaque folder

### ISSUE THREAD

**Issue by Rodrigo294X** [zhuowei/MCPELauncher#654]
I can not make it work. I think it's all right but does not work.
http://www.mediafire.com/download/uud0k71t7w7tjen

**Comment by Rodrigo294X** [comment]
I managed to use by placing the code inside a function newLevel() or function selectLevelHook() so the code was read only when enter in a world. Sorry for bad English. I used a translator. :P

**Comment by officialmcpro32** [comment]
@zhuowei I told you modpkg is broken

**Comment by zhuowei** [comment]
Wow I'm dumb: when a ModPkg is imported, the texture (obviously) doesn't exist, so it just errors out and disables the script. Hopefully fixed in the latest beta by restarting if texture doesn't exist and script is a modPkg.

**Comment by officialmcpro32** [comment]
@Rodrigo294X zhuowei fixed it

**Comment by Rodrigo294X** [comment]
Thx :D
