### ISSUE TITLE
Hola

### ISSUE THREAD

**Issue by marvin222** [zhuowei/MCPELauncher#657]
Me podrian mandar el block launcher para minecraft pe 0.14.0 build 1 porfa

**Comment by zhuowei** [comment]
Build 1? The full release of MCPE 0.14.0 came out a week ago, and BlockLauncher was updated a day later with support. http://tinyw.in/bl if you need the APK for BlockLauncher for 0.14.0

**Comment by marvin222** [comment]
Marvinfloo8879@gmail.com
