### ISSUE TITLE
Intent Action to Import Scripts andor Texture Packs.

### ISSUE THREAD

**Issue by sero583** [zhuowei/MCPELauncher#660]
For Android Developers with which Intent.ACTION_? you can import ModPE Script or Texture Pack. (With that i need help idk which one should i take, i tried some, but all are crashing or not working with BlockLauncher.

**Comment by zhuowei** [comment]
`android.intent.action.VIEW` or `net.zhuoweizhang.mcpelauncher.action.IMPORT_SCRIPT` for scripts, `net.zhuoweizhang.mcpelauncher.action.SET_TEXTUREPACK` for texture packs.

**Comment by sero583** [comment]
Thanks!

**Comment by sero583** [comment]
Intent runfile = new Intent(Intent.ACTION_VIEW);
					runfile.setDataAndType(Uri.parse(gpxfile.getAbsolutePath()), "application/javascript");
					startActivityForResult(runfile);

This is crashing

**Comment by sero583** [comment]
Oops i meant it so:
This following code is crashing:
```
Intent runfile = new Intent(Intent.ACTION_VIEW);
runfile.setDataAndType(Uri.parse(gpxfile.getAbsolutePath()), "application/javascript");
					startActivityForResult(runfile);
```
