### ISSUE TITLE
Using scripts on the server

### ISSUE THREAD

**Issue by KsyMC** [zhuowei/MCPELauncher#668]
'destroyBlock' can be run on the server. Please fix it.
Using threads, add the button.

**Comment by PocketKiller** [comment]
and setGamemode() :+1:

**Comment by zhuowei** [comment]
Fixed.

**Comment by KsyMC** [comment]
net.zhuoweizhang.mcpelauncher.ScriptManager.setLevelFakeCallback(true, false);
This function is to use a script on the server.

**Comment by zhuowei** [comment]
Fixed.
