### ISSUE TITLE
This is not really a big issue for other people but for me IT IS

### ISSUE THREAD

**Issue by hibye32132** [zhuowei/MCPELauncher#669]
I am a multiplayer mod creator, but now blocklauncher doesn't allow connecting to server with mods. Can anyone give me an copy that allows mods on multiplayer and keeps giving me updates? PLEASE help me out!

**Comment by sero583** [comment]
We need a thing like a meta data, which you need to set in PocketMine/BlockLauncher, to tell BL that it can let it the mods enabled, but the default property (if no one isn't set yet) is false (disabled)

```
boolean modsallowed = false;

/*request data from host for example we would say that "request" is the variable which gets it*/
if (request==allowed) {
modsallowed = true;
}
if (request==notallowed) {
modsallowed = true;
}

else {
modsallowed = false;
}

**Comment by zhuowei** [comment]
The server needs to send a special chat message to re-enable scripts.

**Comment by sero583** [comment]
@zhuowei And which message it would be?
