### ISSUE TITLE
Boardwalk not working on Galaxy tab s

### ISSUE THREAD

**Issue by DarkInflictor** [zhuowei/MCPELauncher#673]
Hey, 

I recently downloaded boardwalk on my Samsung Galaxy tab s 8.4 and it keeps giving me an error when I try to launch minecraft. 

Error:java.lang.RuntimeException:java.lang.RuntimeException: Dax returned 6 with error

I have also tried the beta. 

Thanks.

**Comment by zhuowei** [comment]
Unfortunately I'm not working on Boardwalk at this time.
