### ISSUE TITLE
Entity.set/getDroppedItemId(ent);

### ISSUE THREAD

**Issue by Black-DeathPE** [zhuowei/MCPELauncher#677]
Could we have Entity.getDroppedItemId(ent), Entity.getDroppedItemData(ent) and Entity.getDroppedItemAmount(ent)?
(Also please add set versions of those)

This would allow us to know what item's been dropped and set a dropped item's item.

**Comment by TodorGrin** [comment]
Zhuowei, if you want add this functions, you should also add itemDropped(x,y,z,enitity,id,count,data) hook;

**Comment by zhuowei** [comment]
@TodorGrin entityAddedHook works for that

**Comment by zhuowei** [comment]
@Black-DeathPE There's already Entity.getItemEntityId/data/count. There's no set function - I can add them, or you could just use Level.dropItem to create a new drop and get rid of the old one

**Comment by Black-DeathPE** [comment]
Okay, I don't mind, whatever works best :)
