### ISSUE TITLE
Scripts in addons

### ISSUE THREAD

**Issue by Razvan-MCrafter** [zhuowei/MCPELauncher#680]
Like modpkg uses script/main.js it would be awesome to have in the addons in assets/script/main.js
Please add this

**Comment by zhuowei** [comment]
Added in the latest beta.

**Comment by Razvan-MCrafter** [comment]
Thanks

**Comment by zhuowei** [comment]
@Razvan-MCrafter Unfortunately I'm disabling this due to feedback from other people for now. The current beta has support but future versions won't.

**Comment by ISAAC300** [comment]
@zhuowei ;---; i hate you temporaly :P
