### ISSUE TITLE
Broken texture atlas editing

### ISSUE THREAD

**Issue by vaoaboo** [zhuowei/MCPELauncher#682]
Generated atlas is incorrect when you have more than 123 textures in **_images/terrain-atlas/_**. My app **_com.protonge.packs_** relys on Blocklaucher. I would appreciate if you would fix this issue asap. I added one texture pack so you can test it for your self.
[Jolicraft.zip](https://github.com/zhuowei/MCPELauncher/files/149793/Jolicraft.zip)

**Comment by zhuowei** [comment]
@vaoaboo I think I fixed the issue, but the zip of Jolicraft seems to be corrupt (Stone cutter -> glass, pumpkin -> nether stairs?!) so I'm not sure whether I did it right

**Comment by vaoaboo** [comment]
Attached texture pack was broken. Now it works as it should. Thank you for the fix. I will notify you if i find something bugged. Consider it as resolved.
