### ISSUE TITLE
function deathPlayerHook(me,damage){}

### ISSUE THREAD

**Issue by ISAAC300** [zhuowei/MCPELauncher#684]
Level::onPlayerDeath(Player&, EntityDamageSource const&);

very useful for any modders etc

**Comment by zhuowei** [comment]
does mob death hooks not fire for players? I'll take a look.

**Comment by ISAAC300** [comment]
@zhuowei correct

**Comment by zhuowei** [comment]
deathHook fired when I got punched to death by a zombie:
```
function deathHook(attacker, victim) {
	clientMessage(victim + "(" + Entity.getEntityTypeId(victim) + ") died by " + attacker);
}
```
and the clientMessage did display (after I hit respawn)
