### ISSUE TITLE
sendChat does not work.

### ISSUE THREAD

**Issue by KsyMC** [zhuowei/MCPELauncher#687]
net.zhuoweizhang.mcpelauncher.ScriptManager.nativeSendChat
Please Fix!

**Comment by KsyMC** [comment]
Please fix #668

**Comment by ISAAC300** [comment]
Please fix #668 @zhuowei, hi ksymc :3, why you is ignorant?

**Comment by KsyMC** [comment]
@ISAAC300 what?

**Comment by zedman2000** [comment]
I will also stick on here that when acting as a server it does not work either:
https://github.com/zhuowei/MCPELauncher/issues/433

**Comment by ISAAC300** [comment]
@ksymc follow me on twitter and drop a like :3

**Comment by zhuowei** [comment]
Fixed.
