### ISSUE TITLE
Block Launcher does work on my Acer Iconia

### ISSUE THREAD

**Issue by TopStriker-Kydd** [zhuowei/MCPELauncher#688]
Each time i open block launcher it says to install cydia substrate app and then when i do its says its not compatible with my version of minecraft pe. But i have the same version of minecraft pe on my phone (alcatel pixie 3.5) and it works perfectly fine so idk what the problem is on the Acer Iconia

**Comment by zhuowei** [comment]
@TopStriker-Kydd Your Acer Iconia has an Intel Atom processor: while it can run the ARM apk that your phone uses, BlockLauncher only supports the special Atom APK (which is specifically optimized for Intel Atoms). Please purchase Minecraft PE from Google Play (if you didn't purchase MCPE, all of the pirated APKs are for ARM only, so you need to buy legit MCPE)

**Comment by TopStriker-Kydd** [comment]
Minecraft Pocket edition is'nt in my google play for some reason, that's why i downloadedit from another app store....is there like a link or something that you can send me to get the full version?

Sent from Outlook Mobile<http://aka.ms/xp9y6l>



On Wed, Mar 2, 2016 at 4:59 PM -0800, "zhuowei" <notifications@github.com<mailto:notifications@github.com>> wrote:


@TopStriker-Kydd<https://github.com/TopStriker-Kydd> Your Acer Iconia has an Intel Atom processor: while it can run the ARM apk that your phone uses, BlockLauncher only supports the special Atom APK (which is specifically optimized for Intel Atoms). Please purchase Minecraft PE from Google Play (if you didn't purchase MCPE, all of the pirated APKs are for ARM only, so you need to buy legit MCPE)

-

**Comment by QuibblingAsh42** [comment]
Ok, I've got a legit copy of MCPE from the Play Store, and I'm still getting the error.  When I click the link to download the substrate, though, it tells me it's not found.  Where can I find it?
