### ISSUE TITLE
Level.setSignText have a problem

### ISSUE THREAD

**Issue by XFY9326** [zhuowei/MCPELauncher#700]
After I changed the text on a sign,I must wait for nearly one minute to save the text,or it will be disappeared when I open this world again.
Please fix it！

**Comment by zedman2000** [comment]
This has been open for a long time.  The work around is to place another sign NEAR the one you modified with code, then exit the world and re-enter it.
https://github.com/zhuowei/MCPELauncher/issues/224
Super Door Operator 2000 discusses this often on the minecraftforums.net site.
