### ISSUE TITLE
Obj models?

### ISSUE THREAD

**Issue by clienthax** [zhuowei/MCPELauncher#727]
Going through the code for mcpe it seems they have some sort of obj support used for HoloScenes (hololens stuff ?)
the models themselves seem to of been removed in the latest builds but the code is still there for loading them,
would it be possible to use this for entity models?

Also are techne type models limited to the base parts or can we add custom parts?

**Comment by MooGaming227** [comment]
Do you mean like bent/rotated parts?

**Comment by clienthax** [comment]
@MooGaming227 i mean are we limited to just using head/leftarm/rightarm, or can we define custom parts like rightarm1 rightarm2 etc
