### ISSUE TITLE
Does not load following functions:

### ISSUE THREAD

**Issue by iProgramMC** [zhuowei/MCPELauncher#733]
useItem(x,y,z,i,b,s,id,bd), destroyBlock(x,y,z)
Can you help me plz?

**Comment by MooGaming227** [comment]
they work fine for me

**Comment by iProgramMC** [comment]
Have I made a mistake?
function destroyBlock(x,y,z,s){
if(getTile(x,y,z)==220){
setTile(x, y+1, z, 0);
setTile(x, y+2, z, 0);
setTile(x, y+3, z, 0);
Level.dropItem(x,y,z,503,1,0);
if(getTile(x,y,z)==225){
Level.setTile(x,y+1,z,0);
}}

//Item Functions

function useItem(x,y,z,itemId,blockId,side,idv,bdv){ 
if(itemId==503){
setTile(x,y+1,z,220);
setTile(x,y+2,z,221);
setTile(x,y+3,z,222);
setTile(x,y+4,z,223);
Player.addItemInventory(503,-1,0);
}
if(itemId==493){
setTile(x,y+1,z,225);
setTile(x,y+2,z,226);
}
//if(itemId==484)
//t==1
//{
//setTile(x,y+1,z,180);//down
//}
if(itemId==473)
//t==1
{
setTile(x,y+1,z,51);//down
Level.playSound(x,y,z,"fire.ignite",30,100);
}
/*if(itemId==471)
//t==1
{
setTile(x,y+1,z,182);
} */
if(blockId==137 && itemId==331&&aktif==false){
clientMessage("Unknown command. Try /help for a complete list of commands.");
}
if(blockId==137&&itemId==331&&aktif==true){
procCmd(cmn);}
if(blockId==137&&itemId!==331){
ctx.runOnUiThread(new java.lang.Runnable(){
run: function(){ 
try{
GUI = new android.widget.PopupWindow();
var layout = new android.widget.LinearLayout(ctx);
var et = new android.widget.EditText(ctx);
et.setHint("Don't use /");
et.setText(cmns);
var btn = new android.widget.Button(ctx);
btn.setText("Done");
layout.setOrientation(android.widget.LinearLayout.VERTICAL);
layout.addView(et);
layout.addView(btn);
var dialog = new android.app.Dialog(ctx);
dialog.setContentView(layout);
dialog.setTitle("Console Command");
GUI.setHeight(android.widget.LinearLayout.LayoutParams.WRAP_CONTENT);
GUI.setWidth(android.widget.LinearLayout.LayoutParams.WRAP_CONTENT);
GUI.showAtLocation(ctx.getWindow().getDecorView(), android.view.Gravity.TOP, 0, 0);
dialog.show();
btn.setOnClickListener(new android.view.View.OnClickListener(){
onClick: function(view){
var cmn = et.getText();
et.setHint(cmns);
clientMessage("Set console command to /"+cmns);
aktif=true;
dialog.dismiss();
cmns = et.getText().toString();
}
});
} catch (e){
print ("Error: "+e)
ModPE.showTipMessage("Mod has crashed! There is an error in this mod. That error is: " + e);
}
}});
}
}

**Comment by iProgramMC** [comment]
If yes, plz give me the correct functions.( function destroy block(...))

**Comment by MooGaming227** [comment]
function useItem(x,y,z,i,b,s){
if(i==517or whatever # you need){
function here
}
}
function destroyBlock(x, y, z, side){
var blockId = getTile(x, y, z);
if(blockId==193) {//sulfur
  preventDefault();
  setTile(x, y, z, 0);
	SulfurDrop = Math.floor(Math.random() * 2) + 1; 
	if(SulfurDrop == 1){
    Level.dropItem(x,y,z,0,499,2);
	}
	if(SulfurDrop == 2){
    Level.dropItem(x,y,z,0,499,1);
	}
    }

} side is optional

**Comment by MooGaming227** [comment]
Thats the way i use these functions.

**Comment by iProgramMC** [comment]
The code for destroyBlock now works, but the function useItem does not work.

**Comment by iProgramMC** [comment]
That is the whole code I have written://mod by mcpe

function newLevel() {clientMessage(ChatColor.BLUE + "PC Items Mod Minecraft PE Created By");
clientMessage(ChatColor.BLUE + "Andrei The Mine."); 
clientMessage(ChatColor.YELLOW + "Warning In Development!");
clientMessage("Welcome, "+Player.getName(getPlayerEnt())+" Ready to Play");
clientMessage("Minecraft Pocket Edition "+ModPE.getMinecraftVersion());
if (Player.getName(getPlayerEnt())== "Andrei The Mine"){
clientMessage("Hey My Developer!!!");
}}



//Items

ModPE.setFoodItem(512,"mutton_cooked",0,6,"Cooked Mutton");
Player.addItemCreativeInv(512,0);

ModPE.setItem(511, "elytra",0,"Elytra");
Player.addItemCreativeInv(511,0);

ModPE.setFoodItem(510,"mutton_raw",0,1,"Raw Mutton");
Player.addItemCreativeInv(510,0);

ModPE.setItem(509,"broken_elytra",0,"Broken Elytra");
Player.addItemCreativeInv(509,0);

ModPE.setItem(508,"prismarine_crystals",0,"Prismarine Crystals");
Player.addItemCreativeInv(508,0);

ModPE.setFoodItem(507,"chorus_fruit_popped",0,7,"Popped Chorus Fruit");
Player.addItemCreativeInv(507,0);

ModPE.setFoodItem(506,"chorus_fruit",0,1,"Chorus Fruit");
Player.addItemCreativeInv(506,0)

ModPE.setItem(505,"barrier",0,"Barrier");
Player.addItemCreativeInv(505,0);

ModPE.setFoodItem(504,"dragon_breath",0,20,"Dragon Breath Potion");
Player.addItemCreativeInv(504,0);

ModPE.setItem(503,"beacon_item",0,"Beacon");
Player.addItemCreativeInv(503,0);

ModPE.setItem(502,"end_rod",0,"End Rod");
Player.addItemCreativeInv(502,0);

//ModPE.setItem

ModPE.setItem(501,"lead",0,"Lead");
Player.addItemCreativeInv(501,0);

ModPE.setItem(500,"nether_star",0,"Nether Star");
Player.addItemCreativeInv(500,0);

//ModPE.setItem(511,"ruby",0,"Ruby");
//Player.addItemCreativeInv(511,0);

ModPE.setItem(499,"book_writable",0,"Book and Quill");
Player.addItemCreativeInv(499,0);

ModPE.setItem(498,"diamond_horse_armor",0,"Diamond Horse Armor");
Player.addItemCreativeInv(498,0);

ModPE.setItem(497,"gold_horse_armor",0,"Golden Horse Armor");
Player.addItemCreativeInv(497,0);

ModPE.setItem(496,"iron_horse_armor",0,"Iron Horse Armor");
Player.addItemCreativeInv(496,0);

ModPE.setItem(495,"prismarine_shard",0,"Prismarine Shard");
Player.addItemCreativeInv(495,0);

ModPE.setItem(494,"minecart_command_block",0,"Minecart with Command Block");
Player.addItemCreativeInv(494,0);

ModPE.setItem(493, "end_crystal",0,"End Crystal");
Player.addItemCreativeInv(493,0);

//ModPE

ModPE.setItem(489,"ender_eye",0,"Eye of Ender");
Player.addItemCreativeInv(489,0);

ModPE.setItem(480,"quiver",0,"Quiver");
Player.addItemCreativeInv(480,0);

ModPE.setItem(473,"fireball",0,"Fire Charge");
Player.addItemCreativeInv(473,0);

ModPE.setItem(472,"fireworks",0,"Firework Rocket");
Player.addItemCreativeInv(472,0);

//Variables

var randomspawn = 0;
var c;
var t;
var p;
var s;
var m;
var v;
var x;
var y; 
var z; 
var wood = 0;
var enchantlvl= 0;
var aktif= false;
var cmns= "";
var ctx = com.mojang.minecraftpe.MainActivity.currentMainActivity.get(); 
var ho1 = ["cauldron_side", 0];

//Blockd

Block.defineBlock(200,"Prismarine Bricks",[["prismarine_rough",0]],0,false,0);
Player.addItemCreativeInv(200,0);

Block.defineBlock(201,"Sea Lantern", [["sea_lantern",0]],0,false,0);
Block.setLightLevel(201,15);
Player.addItemCreativeInv(201,0);

Block.defineBlock(202, "Crying Obsidian", [["crying_obsidian", 0]],0,false,0);
Player.addItemCreativeInv(202,0);

Block.defineBlock(203, "End Bricks", [["end_bricks", 0]], 0, false, 0);
Player.addItemCreativeInv(203,0);

Block.defineBlock(204, "Prismarine Bricks", [["prismarine_bricks", 0]],0,false,0);
Player.addItemCreativeInv(204,0);

Block.defineBlock(205, "Dark Prismarine", [["prismarine_dark", 0]],0,false,0);
Player.addItemCreativeInv(205,0);

Block.defineBlock(206, "tile.debugblock.name", [["block_debug", 0]],0,false,0);

Block.defineBlock(207, "Chorus Flower", [["chorus_plant",0],["chorus_flower",0],["chorus_plant",0], ["chorus_plant",0], ["chorus_plant",0], ["chorus_plant",0]],0,false,0);
Player.addItemCreativeInv(207,0);

Block.defineBlock(208, "Wet Sponge", [["sponge_wet", 0]],0,false,0);
Player.addItemCreativeInv(208,0);

Block.defineBlock(209, "Purpur Block", [["purpur_block", 0]],0,false,0);
Player.addItemCreativeInv(209,0);

Block.defineBlock(210, "Purpur Pillar", [["purpur_pillar_top", 0],["purpur_pillar_top",0],["purpur_pillar",0], ["purpur_pillar",0], ["purpur_pillar",0], ["purpur_pillar",0]],0,false,0);
Player.addItemCreativeInv(210,0);

Block.defineBlock(211, "Structure Block", [["structure_block", 0]], 0,false,0);
Player.addItemCreativeInv(211,0);

Block.defineBlock(212, "Data Structure Block", [["structure_block_data", 0]],0,false,0);
Player.addItemCreativeInv(212,0);

Block.defineBlock(213, "Corner Structure Block", [["structure_block_corner",0]],0,false, 0);
Player.addItemCreativeInv(213,0);

Block.defineBlock(214, "Load Structure Block", [["structure_block_load", 0]],0,false,0);
Player.addItemCreativeInv(214,0);

Block.defineBlock(215, "Save Structure Block", [["structure_block_save",0]],0,false,0);
Player.addItemCreativeInv(215,0);

Block.defineBlock(216, "White Stained Glass", [["glass_white",0]],0,false,0);
Player.addItemCreativeInv(216,1);
Block.setRenderLayer(216,5);

Block.defineBlock(217, "Dragon Egg", [["dragon_egg", 0]],0,false,0);
Player.addItemCreativeInv(217,0);

Block.defineBlock(218, "Light Gray Stained Glass", [["glass_silver", 0]],0,false,0);
Block.setRenderLayer(218,5);
//Player.addItemCreativeInv(218,0);

Block.defineBlock(219, "Gray Stained Glass", [["glass_gray", 0]] ,0,false,0);
Block.setRenderLayer(219,5);
Player.addItemCreativeInv(219,0);

Block.defineBlock(224, "Black Stained Glass", [ ["glass_black", 0] ], 0, false, 0);
Block.setRenderLayer(224,5);
Player.addItemCreativeInv(224,1);

Block.defineBlock(137, "Command Block", [["command_block", 0]], 0, false, 0);
/*Block.setRedstoneConsumer(137, true); */
Player.addItemCreativeInv(137,0);

Block.defineBlock(225,"endcrystal",[["end_crystal",0]],0,false,0);
Block.setShape(225,0.0625,0.0625,0.0625,0.875,0.875,0.875);
Block.setRenderLayer(225,3);
Block.defineBlock(226,"endcrystalbedrock",[["bedrock",0]],0,false,0);
Block.setShape(226,0,-1,0,1,-0.5,1);
/*Block.defineBlock(225,"banner", [["banner",0]],0,false);
Block.setShape(225,0.45,0.10,0,0.50,1.15,1);
Player.addItemCreativeInv(225,0);

Block.defineBlock(226,"banner", [["planks",0]],0,false);
Block.setShape(226,-1,-1,-1,0,0,0);
Player.addItemCreativeInv(226,0);*/

Block.defineBlock(220,"Beacon", [["glass", 0]], 3, false, 0);
Block.defineBlock(221,"name.beaconobisidian.name", [["obsidian", 0]], 3, false, 0);
Block.defineBlock(222,"name.centerbeacon.name", [["beacon", 0]], 3, false, 0);
/*Block.defineBlock(239,"name.fix.name", [["z", 0]], 3, false, 0);
Block.defineBlock(240,"namd.fix.name", [["zz", 0]], 3, false, 0);*/
Block.defineBlock(223,"name.ray.name", [["beacon_beam", 0]], 3, false, 0);
//SetRenderLayer
Block.setRenderLayer(220, 3);
//SetDestroyTime
Block.setDestroyTime(220, 1);
Block.setDestroyTime(221, 99999*20);
Block.setDestroyTime(222, 99999*20);
Block.setDestroyTime(223, 99999*20);
//SetLightLevel
Block.setLightLevel(220, 1);
Block.setLightLevel(221, 1);
Block.setLightLevel(222, 3);
Block.setLightLevel(223, 7);
//SetLightOpacity
Block.setLightOpacity(220, 0.03);
Block.setLightOpacity(221, 0.03);
Block.setLightOpacity(222, 0.03);
Block.setLightOpacity(223, 0.03);
//SetExplosionResistance
Block.setExplosionResistance(220, true);
//SetShape
Block.setShape(221, 1/16, -1, 1/16, 15/16, -0.8, 15/16);
Block.setShape(222, 3/16, -1.8, 3/16, 13/16, -1.2, 13/16);
Block.setShape(223, 4/16, -2.8, 4/16, 12/16, 128, 12/16);
//DestroyBlock
function destroyBlock(x,y,z,s){
if(getTile(x,y,z)==220){
setTile(x, y+1, z, 0);
setTile(x, y+2, z, 0);
setTile(x, y+3, z, 0);
Level.dropItem(x,y,z,503,1,0);
if(getTile(x,y,z)==225){
Level.setTile(x,y+1,z,0);
}}

//Item Functions

function useItem(x,y,z,i,b,s){ 
if(i==503){
setTile(x,y+1,z,220);
setTile(x,y+2,z,221);
setTile(x,y+3,z,222);
setTile(x,y+4,z,223);
Player.addItemInventory(503,-1,0);
}
if(i==493){
setTile(x,y+1,z,225);
setTile(x,y+2,z,226);
}
//if(i==484)
//t==1
//{
//setTile(x,y+1,z,180);//down
//}
if(i==473)
//t==1
{
setTile(x,y+1,z,51);//down
Level.playSound(x,y,z,"fire.ignite",30,100);
}
}

//Destroy Block Functions

//function destroyBlock(x,y,z,s){}

//Crafting recipes

Item.addShapedRecipe(202,1,0,[
"l,l,l",
"l,o,l",
"l,l,l"],["o",49,0,"l",351,4]);


//Attack Functions

function attackHook(a,v){
if(Player.getCarriedItem(a)==329){
rideAnimal(a,v)}

//Commands

/*function procCmd(coman){
var cit = coman.split(" ");
if(cit[0]=="help"){
clientMessage(ChatColor.GREEN + "---Showing help page 1 of 4 (/help <page>)---");
clientMessage(" /time set <day|night|value>");
clientMessage(" /kill");
clientMessage(" /tp");
clientMessage(" //setblock x y z id data");
}
if(cit[0]=="help"&&cit[1]=="2"){
clientMessage(ChatColor.GREEN + "---Showing help page 2 of 4 (/help <page>)---");
clientMessage(" /tp <x> <y> <z>");
clientMessage(" /gamemode <1|0|c|s|Creative|Survival>");
clientMessage(" /say <");
clientMessage(" /spawnpoint");
}
if(cit[0]=="help"&&cit[1]=="3"){
clientMessage(ChatColor.GREEN + "---Showing help page 3 of 4 (/help <page>)---");
clientMessage(" /summon Entity303 for explosion");
clientMessage(" /help [page|command name]");
clientMessage(" /give <itemId> <amount>");
clientMessage(" /clear");
}
if(cit[0]=="help"&&cit[1]=="4"){
clientMessage(ChatColor.GREEN + "---Showing help page 4 of 4 (/help <page>)---");
clientMessage(" /playsound <sound> <volume> <pitch>");
}
if(cit[0]=="summon"&&cit[1]=="Entity303"){
explode(Player.getX(),Player.getY(),Player.getZ(),100);
}
if(cit[0]=="setblock"){
setTile(cit[1],cit[2],cit[3],cit[4],cit[5]);
clientMessage("Block placed");
}
if(cit[0]=="kill"){
Player.setHealth(-1);
clientMessage("Killed "+Player.getName(getPlayerEnt()));
}
if(cit[0]=="time"&&cit[1]=="set"){
Level.setTime(cit[2]);
}
if(cit[0]=="time"&&cit[1]=="set"&&cit[2]=="day"){
Level.setTime(3000);
}
if(cit[0]=="time"&&cit[1]=="set"&&cit[2]=="night"){
Level.setTime(-8090);
}
if(cit[0]=="gamemode"&&cit[1]=="s"){
clientMessage("Your game mode has been updated");
Level.setGameMode(0);
}
if(cit[0]=="gamemode"&&cit[1]=="c"){
clientMessage("Your game mode has been updated");
Level.setGameMode(1);
}
if(cit[0]=="gamemode"&&cit[1]=="Survival"){
clientMessage("Your game mode has been updated");
Level.setGameMode(0);
}
if(cit[0]=="gamemode"&&cit[1]=="Creative"){
clientMessage("Your game mode has been updated");
Level.setGameMode(1);
}
if(cit[0]=="gamemode"&&cit[1]=="0"){
clientMessage("Your game mode has been updated");
Level.setGameMode(0);
}
if(cit[0]=="gamemode"&&cit[1]=="1"){
clientMessage("Your game mode has been updated");
Level.setGameMode(1);
}
if(cit[0]=="gamemode"&&cit[1]=="3"){
clientMessage("Your game mode has been updated");
}
if(cit[0]=="xp"){
Player.addExp(cit[1]);
clientMessage("Added " + cit[1] + " to " + Player.getName(getPlayerEnt()));
}
if(cit[0]=="summon"&&cit[1]=="Zombie"&&cit[2]==undefined){
clientMessage("Object succesfully summoned");
Level.spawnMob(Player.getX(),Player.getY(),Player.getZ(),32);
}
if(cit[0]=="summon"&&cit[1]=="Zombie"&&cit[2]==1){
clientMessage("Object succesfully summoned");
z=Level.spawnMob(Player.getX(),Player.getY(),Player.getZ(),32);
c=Level.spawnMob(Player.getX(),Player.getY(),Player.getZ(),10);
rideAnimal(z,c);
}
if(cit[0]=="summon"&&cit[1]=="Spider"&&cit[2]==undefined){
clientMessage("Object succesfully summoned");
Level.spawnMob(Player.getX(),Player.getY(),Player.getZ(),35);
}
if(cit[0]=="summon"&&cit[1]=="Enderman"){
clientMessage("Object succesfully summoned");
Level.spawnMob(Player.getX(),Player.getY(),Player.getZ(),38);
}
if(cit[0]=="summon"&&cit[1]=="Pigman"&&cit[2]==undefined){
clientMessage("Object succesfully summoned");
Level.spawnMob(Player.getX(),Player.getY(),Player.getZ(),36);
}
if(cit[0]=="summon"&&cit[1]=="Pigman"&&cit[2]=="1"){
clientMessage("Object succesfully summoned");
p=Level.spawnMob(Player.getX(),Player.getY(),Player.getZ(),36);
c=Level.spawnMob(Player.getX(),Player.getY(),Player.getZ(),10);
rideAnimal(p,c);
}
if(cit[0]=="summon"&&cit[1]=="Creeper"&&cit[2]==undefined){
clientMessage("Object succesfully summoned");
Level.spawnMob(Player.getX(),Player.getY(),Player.getZ(),33);
}
if(cit[0]=="summon"&&cit[1]=="Skeleton"&&cit[2]==undefined){
clientMessage("Object succesfully summoned");
Level.spawnMob(Player.getX(),Player.getY(),Player.getZ(),34);
}
if(cit[0]=="summon"&&cit[1]=="Silverfish"){
clientMessage("Object succesfully summoned");
Level.spawnMob(Player.getX(),Player.getY(),Player.getZ(),39);
}
if(cit[0]=="summon"&&cit[1]=="Slime"){
clientMessage("Object succesfully summoned");
Level.spawnMob(Player.getX(),Player.getY(),Player.getZ(),37);
}
if(cit[0]=="summon"&&cit[1]=="Chicken"){
clientMessage("Object succesfully summoned");
Level.spawnMob(Player.getX(),Player.getY(),Player.getZ(),10);
}
if(cit[0]=="summon"&&cit[1]=="Cow"){
clientMessage("Object succesfully summoned");
Level.spawnMob(Player.getX(),Player.getY(),Player.getZ(),11);
}
if(cit[0]=="summon"&&cit[1]=="Pig"){
clientMessage("Object succesfully summoned");
Level.spawnMob(Player.getX(),Player.getY(),Player.getZ(),12);
}
if(cit[0]=="summon"&&cit[1]=="Sheep"){
clientMessage("Object succesfully summoned");
Level.spawnMob(Player.getX(),Player.getY(),Player.getZ(),13);
}
if(cit[0]=="summon"&&cit[1]=="PrimedTNT"){
clientMessage("Object succesfully summoned");
Level.spawnMob(Player.getX(),Player.getY()+5,Player.getZ(),65);
}
if(cit[0]=="summon"&&cit[1]=="Villager"&&cit[2]=="1"){
clientMessage("Object succesfully summoned");
Level.spawnMob(Player.getX(),Player.getY(),Player.getZ(),15,"mob/villager/villager.png");
}
if(cit[0]=="summon"&&cit[1]=="Villager"&&cit[2]==undefined){
clientMessage("Object succesfully summoned");
Level.spawnMob(Player.getX(),Player.getY(),Player.getZ(),15);
}
if(cit[0]=="summon"&&cit[1]=="Wolf"){
clientMessage("Object succesfully summoned");
Level.spawnMob(Player.getX(),Player.getY(),Player.getZ(),14);
}
if(cit[0]=="summon"&&cit[1]=="MushroomCow"){
clientMessage("Object succesfully summoned");
Level.spawnMob(Player.getX(),Player.getY(),Player.getZ(),16);
}
if(cit[0]=="summon"&&cit[1]=="Spider"&&cit[2]=="1"){
clientMessage("Object succesfully summoned");
s=Level.spawnMob(Player.getX(),Player.getY(),Player.getZ(),34);
p=Level.spawnMob(Player.getX(),Player.getY(),Player.getZ(),35);
rideAnimal(s,p);
}
}*/

//Furnace Recipes

Item.addFurnaceRecipe(510,20,512);
Item.addFurnaceRecipe(506,20,507);

//Death Hook

function deathHook(a,v){
if(Entity.getEntityTypeId(v)== 13){ //checks if that is a sheep
Level.dropItem(Entity.getX(v),Entity.getY(v),Entity.getZ(v),0,510,2,0);
}
}
};
