### ISSUE TITLE
attackHook(attacker, victim) not working correctly.

### ISSUE THREAD

**Issue by DarinM1967** [zhuowei/MCPELauncher#754]
Blocklauncher Pro, on a Pixel C tablet using Marshallow (newest verson) with Minecraft Pocket Edition 0.14.0.

The following code works:

function attackHook(attacker, victim){
   if(attacker == Player.getEntity()) {
      clientMessage("You attacked them!");
   }
}

But, this code doesn't:

function attackHook(attacker, victim){
   if(victim == Player.getEntity()) {
      clientMessage("Your being attacked!");
   }
}

**Comment by DiegoGTRatty** [comment]
Maybe because your is supposed to be you're?

Just kidding, that seems weird though.

**Comment by DarinM1967** [comment]
Possibly...but I doubt it. LOL! Joking a side. Were you able to test and confirm/deny?

**Comment by DiegoGTRatty** [comment]
Yeah, it works fine for me. Maybe because I have the latest "stable" version. AKA I'm a bit outdated but every function works.

**Comment by DarinM1967** [comment]
Thanks for letting me know. What version do you have? I have the newest Pro.

**Comment by DarinM1967** [comment]
Also Peace storm confirmed the bug on ModPE's Git.

**Comment by zhuowei** [comment]
@DarinM1967 I don't think attackHook's supposed to work that way: currently attackHook is only ever called if the attacker is a player.

**Comment by DarinM1967** [comment]
Hmm. Nothing I've read said has ever said that. I've followed several
tutorials and they have always shown that the victim could be the player.
Also why does it say AttackHook(attacker, victim), instead of simply
AttackHook(victim), if attacker is always the Player? Sounds rather
ambiguous to me.

**Comment by zhuowei** [comment]
@DarinM1967 attackHook was originally implemented by Treebl for his ModPE runtime on iOS; when I implemented ModPE for Android attackHook was only called for a player attacking another mob. Maybe his original did call attackHook for other mobs attacking the player, but BlockLauncher never did.

I'll add an entityHurtHook or something that will be called whenever an entity gets hurt, so that you can check for other entities attacking player.

**Comment by DarinM1967** [comment]
Anyway thanks zhuiwei. Do you know where I can find a list with accurate
descriptions for the functions & hooks since everywhere I look for them I
run into errors?

**Comment by DarinM1967** [comment]
Hey thanks zhuowei. I guess I'll have to dig in the source code so I can
figure out what works with what. Is it well documented?

**Comment by zhuowei** [comment]
@DarinM1967 The current source code is old (I stopped releasing source in 2014-ish) but a lot of the stuff remains the same. Unfortunately I haven't documented much of the api, but Connor's wiki is pretty good https://github.com/Connor4898/ModPE-Docs and if you need a list of all the functions and hooks you can go to Launcher Settings -> Nerdy Stuff -> Dump ModPE script methods

**Comment by zhuowei** [comment]
@DarinM1967 Added entityHurtHook, which is called whenever any entity/mob gets hurt. (attacker will be -1 if attacked by block/drowning, etc)

**Comment by DarinM1967** [comment]
Zhuowei your "Da' Man!". Thank you!
