### ISSUE TITLE
function deathHook(m,v)is broken

### ISSUE THREAD

**Issue by KenMizz** [zhuowei/MCPELauncher#755]
var money=0
function deathHook(m,v){
	if(v==EntityType.ZOMBIE){
		money=money+2
		ModPE.showTipMessage("money:"+money+"\nmoney+2")
		}
		}
It doesn't work
plz fix it
@zhuowei

**Comment by DiegoGTRatty** [comment]
Replace 
`EntityType.ZOMBIE`

with
`32`

**Comment by zhuowei** [comment]
@DiegoGTRatty that shouldn't happen: will take a look at it

**Comment by Rodrigo294X** [comment]
you can use: if(Entity.getEntityTypeId(v)==32)

**Comment by zhuowei** [comment]
@KenMizz Yeah, @Rodrigo294X Rodrigo is right; the correct code is
```
if(Entity.getEntityTypeId(v)==EntityType.ZOMBIE)
```.

Good catch.
