### ISSUE TITLE
Crashes everytime when i destroy an object.

### ISSUE THREAD

**Issue by Sotiris021** [zhuowei/MCPELauncher#763]
I am playing it on Motorola Moto G 3rd Gen 
Android Marshmallow 6.0.
By the way i haven't installed any mods.

**Comment by zhuowei** [comment]
@Sotiris021 I'm on a Nexus 6P on 6.0.1 and I'm not experiencing this: Which version of MCPE, any texture packs?

**Comment by Sotiris021** [comment]
@zhuowei I'm am using Version 0.14.0 of MCPE.
I don't have any texture packs.But when i enable safe mode,everything works well.

**Comment by Sotiris021** [comment]
@zhowei Well for a reason now it doesn't crash.I just rebooted the phone..And all things are fixed..

**Comment by Sotiris021** [comment]
I've reported an issue when i have world edit mod.
(It crashes when i destroy something or attack)

**Comment by Sotiris021** [comment]
@zhuowei Hi, today you uploaded a new uptade of Block launcher. Well i saw that one guy had the same phone with me and had the same problem as me...
I uptaded the launcher but, the same problem happens,when i have mods option enabled,it crashes.But i downloaded the beta that you gave that guy #776 (This one: http://zhuoweizhang.net/MCPELauncher/MCPELauncherApp-release-beta.apk ) and everything workes no crashes or anything.Do you know why? Or do you want me to bug report this problem or something..?



(What i use: Motorola Moto G 3rd Gen With Android:Marshmallow 6.0 and Minecraft 0.14.0)

**Comment by zhuowei** [comment]
@sotiris021 yes, please take a bugreport: 1.12.4 is directly based on that beta, and I released it specifically to fix this problem.

**Comment by Sotiris021** [comment]
@zhuowei Here there are the links of the bug reports:
https://drive.google.com/file/d/0B066cV2c1fMrQ2RnVTc1MGZmNmM/view?usp=docslist_api
And
https://drive.google.com/file/d/0B066cV2c1fMrYU5uOU80bXdqTWM/view?usp=docslist_api

Hopefully it could be fixed!
By the way you have done a great work with this app.I've used the first releases and i have been impressed with all this improvements on the new one's!!

**Comment by zhuowei** [comment]
@Sotiris021 I have no idea why the crash happens (It kinda looks like one piece of test code was running when it's not possible for it to run ever), so I just did a clean rebuild: http://zhuoweizhang.net/MCPELauncher/MCPELauncherApp-release-beta.apk does this beta work?

**Comment by Sotiris021** [comment]
@zhuowei Yes, the beta that you gave me works!!
No problems found.
