### ISSUE TITLE
Recently added "entityHurtHook" doesn't appear to work!

### ISSUE THREAD

**Issue by DarinM1967** [zhuowei/MCPELauncher#772]
Created the following script to test new hook:

function entityHurtHook(attacker, victim) {
	if(attacker != EntityType.Player) {
	   clientMessage("You have been hurt!");
	}
   else {
   	clientMessage("You hurt them!");
   }
}

Created new world, waited till night, got attacked by spiders & zombies and let them beat on me till "You Died!", but no client messages were generated.  Could someone test to confirm? Thanks!

P.S. Also ran another "modpescript_dump.txt" from Block Launcher Pro, but hook wasn't listed.

**Comment by SuprD** [comment]
I can confirm that it works. You probably just forgot to install the latest beta. Also, you need to change <code>if(attacker != EntityType.Player) {</code> to <code>if(Entity.getEntityTypeId(attacker) != EntityType.PLAYER) {</code> .

**Comment by DarinM1967** [comment]
Thanks SuprD, but everything is updated (ModPE Pro, BlockLauncher Pro,
MCPE) and tried the following script:

function entityHurtHook(attacker, victim) {
if(Entity.getEntityTypeId(attacker) != EntityType.PLAYER) {
   clientMessage("You have been hurt!");
}
   else {
   clientMessage("You hurt them!");
   }
}

But still doesn't work.

**Comment by Black-DeathPE** [comment]
Don't use EntityType.PLAYER, use Player.getEntity(). EntityType.PLAYER is the entity type of players and Player.getEntity() is the player entity.

**Comment by DarinM1967** [comment]
Black-DeathPE thanks for the suggestion, but modified the script as in the
following:

function entityHurtHook(attacker, victim) {
if(Entity.getEntityTypeId(attacker) != Player.getEntity()) {
   clientMessage("You have been hurt!");
}
   else {
   clientMessage("You hurt them!");
   }
}

But still doesn't work.

**Comment by DarinM1967** [comment]
I don't run mods only .js scripts and currently have no problem with any of
them, so don't get it.

**Comment by SuprD** [comment]
I meant the latest BlockLauncher beta, which is the free version. BlockLauncher Pro in the Play Store hasn't received this function yet. Use the free version: http://zhuoweizhang.net/MCPELauncher/MCPELauncherApp-release-beta.apk

**Comment by DarinM1967** [comment]
Oh sorry didn't understand you clearly. Thanks for the update. Wonder when
it will be in new pro version (hate ads).

**Comment by Black-DeathPE** [comment]
Change Entity.getEntityTypeId(attacker) to attacker

**Comment by TrinityDevelopers** [comment]
:+1: @Black-DeathPE

**Comment by DarinM1967** [comment]
In the beta/free or in the Pro/Paid version?

**Comment by DarinM1967** [comment]
Installed newest version of Block launcher (free) from playtime and tried
the following script:

function entityHurtHook(attacker, victim) {
if(Entity.getEntityTypeId(attacker) != Player.Entity() ) {
   clientMessage("You have been hurt!");
}
   else {
   clientMessage("You hurt them!");
   }
}

Also tried just:

function entityHurtHook(attacker, victim) {
if(attacker != Player.Entity() {
   clientMessage("You have been hurt!");
}
   else {
   clientMessage("You hurt them!");
   }
}

But neither worked. Is there another beta version I should know about?

In the beta/free or in the Pro/Paid version?

**Comment by TrinityDevelopers** [comment]
It is Player.getEntity() not Player.Entity()

**Comment by DarinM1967** [comment]
Sorry I edited the last message with my phone.

I tried:

function entityHurtHook(attacker, victim) {
if(Entity.getEntityTypeId(attacker) != Player.getEntity()) {
   clientMessage("You have been hurt!");
}
   else {
   clientMessage("You hurt them!");
   }
}
and:

function entityHurtHook(attacker, victim) {
if(attacker != Player.getEntity()) {
   clientMessage("You have been hurt!");
}
   else {
   clientMessage("You hurt them!");
   }
}

But neither worked. Got killed trying both, but no messages appeared.
Uninstalled and reinstalled BlockLauncher (Free) to test with. Also did a
ModPe_dump.txt and didn't show up in the list.

**Comment by DarinM1967** [comment]
Sorry don't know why it generated all that white space between statements
either, but script doesn't have that amount.

**Comment by SuprD** [comment]
Weird. My modpe dump does have it listed. Are you sure you used the beta from the link I gave earlier (not the free version in the Play Store)?

And just for clarification, use either <code>(attacker != Player.getEntity())</code> or <(Entity.getEntityTypeId(attacker) != EntityType.PLAYER)</code>. The first checks if it's the main player, the second checks for any player. You probably want the first one.

**Comment by DarinM1967** [comment]
Sorry missed the link. I downloaded, installed beta, tested it and can
confirm that it does work properly. Thanks guys I really appreciated all of
your help and patients. Can't wait till its on the Pro version.

**Comment by zhuowei** [comment]
Pro 1.12.4 is being uploaded: Closing, and thanks for the suggestion.

**Comment by DarinM1967** [comment]
Just updated BlockLauncher Pro to 1.12.4, tested
function.EntityHurt(attacker, victim) and it works correctly! Thanks for
the new function!!!
