### ISSUE TITLE
Crashes every time I attack or break a block

### ISSUE THREAD

**Issue by timberstar** [zhuowei/MCPELauncher#776]
I have a moto g3(3rd generation)
Mcpe 0.14.0 
Android 6.0 marshmallow. And it keeps crashing even though I don't have any mods or texture packs or anything at all. Please help me.

**Comment by zedman2000** [comment]
Hey there,
What version of Block Launcher are you using?

If you open the same world in PLAIN MCPE, is everything okay?
Do you have desktop mode enabled?  Any add-ons?  Can you disable the add-ons (it is on by default), even if you do not have any installed.
What tool are you using to break the block?  Which block is it?  

I had a similar issue once on my Nexus 5.  I got around it by creating a new world in PLAIN MCPE.  Then I would break 1 block, exit the world.  Then I could go back into BL and everything would work as expected.

Hope that helps!

**Comment by timberstar** [comment]
I'm using the unpaid version. And yes it is okay in plain mcpe. I don't know what desktop is. Don't know what add ons are. I'm not using any tool to break the block or attack. And it's any block. And any mob I attack it crashes. Thanks for your help! :)

**Comment by timberstar** [comment]
I tried what you did and it crashes right when the block breaks

**Comment by zedman2000** [comment]
Did you download from the Playstore or from GitHub?
Regarding what version of block launcher, I meant, clock on the wrench, launcher options, swipe down to about block launcher and click that.  That numbers are listed?

Regarding Desktop Mode, that is a selection about 1/2 way down the options "Use Desktop GUI"
Regarding the Add-Ons, it doesn't matter if you know what they are.  I would like you to disable the feature.  In the same menu area, 4th from the top, click that from "On" to "Off"

**Comment by timberstar** [comment]
I turned off the add ons  and use desktop GUI is off and the version of block launcher is:1.12.2

**Comment by timberstar** [comment]
I got block launcher from Google play store

**Comment by zedman2000** [comment]
@timberstar that is strange.  Have you tried putting a mod on?  I actually do not think I have EVER used Block Launcher without at least 1 script installed and running. 

Aside from that, I think this is out of my league, maybe someone else or @zhuowei has a suggestion.  As I said, I resolved my issue with using MCPE to create a world before accessing it with Block Launcher.  I also asked if you got it from the Play Store, since that will ensure you get the correct version and type.  I am sorry I could not be more help, but as I said, maybe someone else has a suggestion.

**Comment by timberstar** [comment]
Yes I have tried it with a mod too. Could you refer me to zhouwei please?

**Comment by zedman2000** [comment]
I did.  :-)  See the @ zhuowei in my last post?  That tags him.  Keep in mind Time-zones, he might not get back to you right away.  There should also be an e-mail contact in the PlayStore.

**Comment by timberstar** [comment]
OK thanks so much! :)

**Comment by ISAAC300** [comment]
Leave a commentis treteretatrrwtegrtetrtetatatatataaarraarasss Leave a commentis treteretatrrwtegrtetrtetatatatataaarraarasss Leave a commentis treteretatrrwtegrtetrtetatatatataaarraarasss Leave a commentis treteretatrrwtegrtetrtetatatatataaarraarasss Leave a commentis treteretatrrwtegrtetrtetatatatataaarraarasss Leave a commentis treteretatrrwtegrtetrtetatatatataaarraarasss Leave a commentis treteretatrrwtegrtetrtetatatatataaarraarasss Leave a commentis treteretatrrwtegrtetrtetatatatataaarraarasss Leave a commentis treteretatrrwtegrtetrtetatatatataaarraarasss Leave a commentis treteretatrrwtegrtetrtetatatatataaarraarasss Leave a commentis treteretatrrwtegrtetrtetatatatataaarraarasss Leave a commentis treteretatrrwtegrtetrtetatatatataaarraarasss Leave a commentis treteretatrrwtegrtetrtetatatatataaarraarasss Leave a commentis treteretatrrwtegrtetrtetatatatataaarraarasss Leave a commentis treteretatrrwtegrtetrtetatatatataaarraarasss Leave a commentis treteretatrrwtegrtetrtetatatatataaarraarasss Leave a commentis treteretatrrwtegrtetrtetatatatataaarraarasss Leave a commentis treteretatrrwtegrtetrtetatatatataaarraarasss Leave a commentis treteretatrrwtegrtetrtetatatatataaarraarasss Leave a commentis treteretatrrwtegrtetrtetatatatataaarraarasss Leave a commentis treteretatrrwtegrtetrtetatatatataaarraarasss Leave a commentis treteretatrrwtegrtetrtetatatatataaarraarasss Leave a commentis treteretatrrwtegrtetrtetatatatataaarraarasss Leave a commentis treteretatrrwtegrtetrtetatatatataaarraarasss Leave a commentis treteretatrrwtegrtetrtetatatatataaarraarasss Leave a commentis treteretatrrwtegrtetrtetatatatataaarraarasss Leave a commentis treteretatrrwtegrtetrtetatatatataaarraarasss Leave a commentis treteretatrrwtegrtetrtetatatatataaarraarasss Leave a commentis treteretatrrwtegrtetrtetatatatataaarraarasss Leave a commentis treteretatrrwtegrtetrtetatatatataaarraarasss Leave a commentis treteretatrrwtegrtetrtetatatatataaarraarasss Leave a commentis treteretatrrwtegrtetrtetatatatataaarraarasss Leave a commentis treteretatrrwtegrtetrtetatatatataaarraarasss Leave a commentis treteretatrrwtegrtetrtetatatatataaarraarasss Leave a commentis treteretatrrwtegrtetrtetatatatataaarraarasss Leave a commentis treteretatrrwtegrtetrtetatatatataaarraarasss Leave a commentis treteretatrrwtegrtetrtetatatatataaarraarasss Leave a commentis treteretatrrwtegrtetrtetatatatataaarraarasss Leave a commentis treteretatrrwtegrtetrtetatatatataaarraarasss Leave a commentis treteretatrrwtegrtetrtetatatatataaarraarasss Leave a commentis treteretatrrwtegrtetrtetatatatataaarraarasss Leave a commentis treteretatrrwtegrtetrtetatatatataaarraarasss Leave a commentis treteretatrrwtegrtetrtetatatatataaarraarasss

**Comment by ISAAC300** [comment]
Leave a commentis treteretatrrwtegrtetrtetatatatataaarraarasss Leave a commentis treteretatrrwtegrtetrtetatatatataaarraarasss Leave a commentis treteretatrrwtegrtetrtetatatatataaarraarasss Leave a commentis treteretatrrwtegrtetrtetatatatataaarraarasss Leave a commentis treteretatrrwtegrtetrtetatatatataaarraarasss Leave a commentis treteretatrrwtegrtetrtetatatatataaarraarasss Leave a commentis treteretatrrwtegrtetrtetatatatataaarraarasss Leave a commentis treteretatrrwtegrtetrtetatatatataaarraarasss Leave a commentis treteretatrrwtegrtetrtetatatatataaarraarasss Leave a commentis treteretatrrwtegrtetrtetatatatataaarraarasss Leave a commentis treteretatrrwtegrtetrtetatatatataaarraarasss Leave a commentis treteretatrrwtegrtetrtetatatatataaarraarasss Leave a commentis treteretatrrwtegrtetrtetatatatataaarraarasss Leave a commentis treteretatrrwtegrtetrtetatatatataaarraarasss Leave a commentis treteretatrrwtegrtetrtetatatatataaarraarasss Leave a commentis treteretatrrwtegrtetrtetatatatataaarraarasss Leave a commentis treteretatrrwtegrtetrtetatatatataaarraarasss Leave a commentis treteretatrrwtegrtetrtetatatatataaarraarasss Leave a commentis treteretatrrwtegrtetrtetatatatataaarraarasss Leave a commentis treteretatrrwtegrtetrtetatatatataaarraarasss Leave a commentis treteretatrrwtegrtetrtetatatatataaarraarasss Leave a commentis treteretatrrwtegrtetrtetatatatataaarraarasss Leave a commentis treteretatrrwtegrtetrtetatatatataaarraarasss Leave a commentis treteretatrrwtegrtetrtetatatatataaarraarasss Leave a commentis treteretatrrwtegrtetrtetatatatataaarraarasss Leave a commentis treteretatrrwtegrtetrtetatatatataaarraarasss Leave a commentis treteretatrrwtegrtetrtetatatatataaarraarasss Leave a commentis treteretatrrwtegrtetrtetatatatataaarraarasss Leave a commentis treteretatrrwtegrtetrtetatatatataaarraarasss Leave a commentis treteretatrrwtegrtetrtetatatatataaarraarasss Leave a commentis treteretatrrwtegrtetrtetatatatataaarraarasss Leave a commentis treteretatrrwtegrtetrtetatatatataaarraarasss Leave a commentis treteretatrrwtegrtetrtetatatatataaarraarasss Leave a commentis treteretatrrwtegrtetrtetatatatataaarraarasss Leave a commentis treteretatrrwtegrtetrtetatatatataaarraarasss Leave a commentis treteretatrrwtegrtetrtetatatatataaarraarasss Leave a commentis treteretatrrwtegrtetrtetatatatataaarraarasss Leave a commentis treteretatrrwtegrtetrtetatatatataaarraarasss Leave a commentis treteretatrrwtegrtetrtetatatatataaarraarasss Leave a commentis treteretatrrwtegrtetrtetatatatataaarraarasss Leave a commentis treteretatrrwtegrtetrtetatatatataaarraarasss Leave a commentis treteretatrrwtegrtetrtetatatatataaarraarasss Leave a commentis treteretatrrwtegrtetrtetatatatataaarraarasss

**Comment by zhuowei** [comment]
@zedman2000 @timberstar Can you please take a bug report after the crash? After a crash, please follow https://www.youtube.com/watch?v=YxQ3NTloD2c, upload the crash log to something like Dropbox or Google Drive, and paste a link here

**Comment by timberstar** [comment]
Here are the links @zhuowei https://drive.google.com/file/d/0ByACl26H4uC9TDFwRTIwTi1ZNUk/view?usp=docslist_api
https://drive.google.com/file/d/0ByACl26H4uC9WnNCMnJFcU9WMEU/view?usp=docslist_api

**Comment by timberstar** [comment]
Thanks for helping me. I greatly appreciate it! :)

**Comment by timberstar** [comment]
Are you trying to find out what's wrong based on the bug reports?

**Comment by timberstar** [comment]
@zhuowei did you figure out what is going on?

**Comment by zhuowei** [comment]
@timberstar Can you please try http://zhuoweizhang.net/MCPELauncher/MCPELauncherApp-release-beta.apk ? It looks like my entity added hook is crashing when the block spawns the dropped block.

**Comment by timberstar** [comment]
It works! :D thank you so much @zhuowei ! I can now play modded survival with my friend. Your service is the best. Rating 5 star review on Google play! Thanks again my man!

**Comment by zhuowei** [comment]
@timberstar Thanks: I'm uploading 1.12.4 on Google Play right now.
