### ISSUE TITLE
Please tell us...

### ISSUE THREAD

**Issue by GenbuHase** [zhuowei/MCPELauncher#791]
Hello! I'm Japanese, so I couldn't tell you well...
Nowadays, what you said occured a case in Japan.

I want to ask the content.
Please contact me as quickly as you could...

**Comment by GenbuHase** [comment]
You said "I don't admit what users of BlockLauncher use any mods on multiplay.", didn't you??

**Comment by zhuowei** [comment]
What do you mean? I know that some people cheat with scripts in multiplayer, but I've been trying to block that in recent BlockLauncher versions...

**Comment by GenbuHase** [comment]
@zhuowei
Please look at the contents of the link...
https://plus.google.com/+Castella0216/posts/dZVvPkjo4y2

You may can't read in Japanese.
In conclusion, you don't let us use Mods in multiplay?

**Comment by zhuowei** [comment]
@GenbuHase If a server wants to allow mods in multiplayer, they can do that by sending a special chat message to BlockLauncher when the user logs in. Otherwise mods will be disabled in servers. LAN worlds will still have mod support.

**Comment by GenbuHase** [comment]
@zhuowei
OK.
Thank you for your help, Mr. zhuowei!!

**Comment by GenbuHase** [comment]
@zhuowei
I have what I want you to do.
Japanese People wanna be able to use Mods in multiplay.

I think it's difficult to do...
Please fix the system for us......

**Comment by nao20010128nao** [comment]
@zhuowei Could you tell us what message can enable Mods?

**Comment by GenbuHase** [comment]
@nao20010128nao
Naoさん参戦((((((
