### ISSUE TITLE
Please tell me about ModPE.dumpVtable...

### ISSUE THREAD

**Issue by GenbuHase** [zhuowei/MCPELauncher#800]
Good morning! I'm Japanese, so I mayn't tell a content well...
We are members of community of Minecraft PE in Japan.

Please tell me how to use [ModPE.dumpVtable].
We also edit the ModdingWiki.

I wanna write the content which is about [ModPE.dumpVtable]...

**Comment by zhuowei** [comment]
Dumps a vtable to LogCat. First parameter is name of class, second parameter is size. Completely useless unless you're an addon developer. Example: ModPE.dumpVtable("Entity", 1024)

**Comment by TrinityDevelopers** [comment]
How do you find what the size of the vtable is?
