### ISSUE TITLE
plz Update Hook

### ISSUE THREAD

**Issue by KenMizz** [zhuowei/MCPELauncher#804]
Block.setDestroyTime(BlockID,time,BlockData)
Block.setShape(BlockID,x1,y1,z1,x2,y2,z2,BlockData)
Block.setExplosionResistance(BlockID,number,BlockData)
 Block.setLightLevel(BlockID,number,BlockData)
 Block.setRenderLayer(BlockID,RenderType,BlockData)
Plz Update it,BlockData will be useful
@zhuowei Thanks<3

**Comment by officialmcpro32** [comment]
@KenMizz Block.setShape supports block data do it like this Block.setShape(ID,x,y,z,x,y,zBlockData);

**Comment by KenMizz** [comment]
@zhuowei
