### ISSUE TITLE
bl_setArmorTexture is broken

### ISSUE THREAD

**Issue by Razvan-MCrafter** [zhuowei/MCPELauncher#810]
In the last update bl_setArmorTexture doesn't work anymore. The armor is transparent. It worked in the latest update

**Comment by zhuowei** [comment]
@Razvan-MCrafter Link to the mod and texture pack please?

**Comment by Razvan-MCrafter** [comment]
@zhuowei it's an addon https://play.google.com/store/apps/details?id=razvanmccrafter.addon.emeralditems

**Comment by TrinityDevelopers** [comment]
It really does not help giving a compiled mod.  He needs to see the source too.

**Comment by Razvan-MCrafter** [comment]
I just used the code from his example https://github.com/zhuowei/MCPELauncher-addons/tree/master/makeitemexample

**Comment by Razvan-MCrafter** [comment]
I found the problem, I activated ModPE scripts and now it works. Can you make this function available even when ModPE scripts are off?
