### ISSUE TITLE
Crashes on N preview

### ISSUE THREAD

**Issue by zhuowei** [zhuowei/MCPELauncher#811]
(/`_`)/ _|____|_ OpenJDK.
https://twitter.com/Yroki_invasion/status/710957415110287360

**Comment by Yroki12** [comment]
I sent this tweet.
On N, I tried to send bug report, but couldn't send bug report.
I watched a movie on youtube which you told me how to send bug report and I did in this way.
why can't I send bug report?

**Comment by zhuowei** [comment]
@Yroki12 Fixed in latest beta. Thanks!
