### ISSUE TITLE
New Hook

### ISSUE THREAD

**Issue by KenMizz** [zhuowei/MCPELauncher#819]
Player.getRunSpeed(Playername)
Player.setRunSpeed(Playername,number)
It ll be useful
plz add it<3

**Comment by KenMizz** [comment]
Wait..
Entity.getRunSpeed(entity)
Entity.setRunSpeed(entity,number)
<3
@zhuowei

**Comment by Davidm16** [comment]
@KenMizz  Entity.addEffect(entity,MobEffect.movementSpeed,time,0,false,false)

**Comment by DiegoGTRatty** [comment]
@KenMizz 
> ```
Entity.getRunSpeed(entity);
Entity.setRunSpeed(entity,number);
```

@Davidm16 
> `Entity.addEffect(entity,MobEffect.movementSpeed,time,0,false,false);`

What David is trying to say is that you could use the Entity.addEffect() functions to achieve this.

Either what David mentioned for a faster speed, or:
`Entity.addEffect(entity, MobEffect.movementSlowdown, time, 0, false, false);`
for a slower speed.

**Comment by TrinityDevelopers** [comment]
It's simple: Entity.getVelX(entity), Entity.getVelY(entity), and Entity.getVelZ(entity);  
You can use these functions to calculate an Entity's speed.

**Comment by DiegoGTRatty** [comment]
@TrinityDevelopers 
> It's simple: ```
Entity.getVelX(entity);
Entity.getVelY(entity);
Entity.getVelZ(entity);
```

With all the new stuff I forgot this existed. :v

**Comment by TrinityDevelopers** [comment]
lol cool
