### ISSUE TITLE
function question

### ISSUE THREAD

**Issue by KenMizz** [zhuowei/MCPELauncher#825]
How to use function redstoneUpdateHook?
:/

**Comment by THERALWEAN231** [comment]
I'm the best at marking redstone code but here is some example code of a block that is you power it by red stone it will teleport you to the coords

Block.defineBlock(item id, "teleport block", [["diamond_block", 0], ["diamond_block", 0], ["diamond_block", 0], ["diamond_block", 0], ["diamond_block", 0], ["diamond_block", 0]]);


Block.setRedstoneConsumer(item id,true);

function redstoneUpdateHook(x,y,z,newCurrent,worldLoading,blockId,blockDamage) {

		var powered = newCurrent;

if(blockId == item id && powered >= 1 && powered <= 15){
Entity.setPosition(getPlayerEnt(), 2084, 58, 27);
}}

Hope this helps

**Comment by KenMizz** [comment]
@THERALWEAN231 Thanks bro:)
