### ISSUE TITLE
attackHook Bug?

### ISSUE THREAD

**Issue by MooGaming227** [zhuowei/MCPELauncher#826]
function attackHook(a,v){
    	
if (Entity.getNameTag(_**does a go here because that doesnt work either**_)=="T-Rex"){
Entity.setHealth(v, Entity.getHealth(v) - dmg);
}	
}

This still doesnt do 10 damage only half a heart.
Am i doing something wrong? it also doesnt work with getmobskin or get rendertype.

**Comment by Danil6969** [comment]
What value is "dmg" field or variable is equal to?

**Comment by MooGaming227** [comment]
i have a global variable  = 10

**Comment by SuprD** [comment]
Try entityHurtHook(a,v,halfhearts) instead. attackHook only works with players.

**Comment by MooGaming227** [comment]
ok thx.
