### ISSUE TITLE
[i need ideas] for make API :v

### ISSUE THREAD

**Issue by ISAAC300** [zhuowei/MCPELauncher#837]
give me ideas pls.
for my ModPEPlus Library.

**Comment by sliceofcode** [comment]
Uhhhh...this isn't the place for discussion?

**Comment by ISAAC300** [comment]
@sliceofcode eiddik detceted

**Comment by TrinityDevelopers** [comment]
Yeah, not a place to discuss.  Move this to your repository
(close this zhuowei)

**Comment by ISAAC300** [comment]
fuck off :)

**Comment by ISAAC300** [comment]
i have ideas now, closing now.
