### ISSUE TITLE
attackHook cant use fuctions based off of attacker

### ISSUE THREAD

**Issue by MooGaming227** [zhuowei/MCPELauncher#840]

**Comment by MooGaming227** [comment]
function attackHook(a,v){
if(Entity.getMobSkin(a)=="mob/dinos/trex_wild.png"){
clientMessage("The Function Is called");
Entity.setHealth(v, Entity.getHealth(v) - 10);
}	
}

Im not even getting the client messgae

**Comment by TrinityDevelopers** [comment]
That is because attackHook is designed for only when the player attacks, not when a mob attacks.  (or at least I'm very sure that is the case)

**Comment by MooGaming227** [comment]
Ok thank you i figured it out. How do i clod-se issue?

**Comment by MooGaming227** [comment]
nvm
