### ISSUE TITLE
Asus Users are not compatible

### ISSUE THREAD

**Issue by Kairu25** [zhuowei/MCPELauncher#877]
When will you update the Blocklauncher to be compatible with the Asus Devices?

**Comment by Rodrigo294X** [comment]
I have an Asus and it works for me. I think you are referring to devices with Intel (x86) processor. In this case you need to install MCPE from google  play store, so you will install a "special" version for these devices. Most apks found on the internet are ARM and then not compatible with mods, if installed on x86 devices. (Or find a good friend who also has an x86 device and ask him to generate an apk for you)

**Comment by Kairu25** [comment]
Ok thanks...I bought MCPE on my other account, maybe I'll install it later and check if it works :D

**Comment by zedman2000** [comment]
Please close this if you are not sure.  You can always re-open this later on if you finally do test and find there is an issue.  I use this on x86 and arm without any issues (I use the Google Play Store version).  We do not want to take up more of @zhuowei 's time reading things that he could better spend on other issues.

**Comment by dinisgamer** [comment]
Its not only on asus its on intel processators I have a acer Iconia One 7 and blocklauncher not works. But the 0.12.4 add support for intel. But the version 0.12.7 not works again
