### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by c0rt3xg4m1ng** [zhuowei/MCPELauncher#897]
Recently, I was testing my texture pack. And it had a error...

Since then, if i go to:
-Launcher options
-ModPE Scripts
-Texture Pack

The app just restarts... I tried re-installing but it did not work. :/ 

My device's specs:
CPU-MT6572
OS-ANDROID 4.2.2
ROM-ALLIVE OS (Marshmallow Themed)
RAM-512MB (325 MB VRAM)
DISPLAY-480x800

Please fix it Because I'm testing my Mod and Texture pack...

                                     -c0rt3xg4m1ng

**Comment by c0rt3xg4m1ng** [comment]
Pls fix it ASAP... :/

**Comment by WIPocket** [comment]
Try to delete the block-lounchers data folder in /sdcard/Android/data

**Comment by c0rt3xg4m1ng** [comment]
Nope, didnt work...

I fixed it by restoring a recent nandroid backup...

**Comment by c0rt3xg4m1ng** [comment]
I fixed it by restoring a recent nandroid backup... :/
