### ISSUE TITLE
[ModPE.openInputStreamFromTexturePack] is not working.

### ISSUE THREAD

**Issue by GenbuHase** [zhuowei/MCPELauncher#898]
I'm Japanese, so I mayn't be able to tell you well.

`ModPE.openInputStreamFromTexturePack` is not working.
I want to use for developing a Mod.

I've waited it's support for 3 month ago.
If you can use it, please tell me about it...

**Comment by Black-DeathPE** [comment]
Desno365 uses it in his Portal 2 & DesnoGuns mod, maybe look through his code and see if you can understand what it does

**Comment by GenbuHase** [comment]
@Black-DeathPE
nnn...
My mod can be used before, but it can't now...

**Comment by zhuowei** [comment]
Please post your code and texture pack?

**Comment by GenbuHase** [comment]
@zhuowei 
Sure!
Please download from this link.

**Comment by GenbuHase** [comment]
[Rewrited]
I could these codes yesterday.
It has already fixed.

Thank you.
