### ISSUE TITLE
New Hook

### ISSUE THREAD

**Issue by KenMizz** [zhuowei/MCPELauncher#982]
FurnaceBlockEntity::isFuel(ItemInstance const*);
Item.addFurnaceFuel(ItemID,Time)
maybe?

**Comment by KenMizz** [comment]
bool (*isfuel_)(ItemInstance const*);
bool isfuel(ItemInstance const*iis)
{
	if(iis->getId()==1)
		return true;
	else return isfuel_(iis);
}
JNIEXPORT jint JNI_OnLoad(JavaVM*,void*)
{
	MSHookFunction((void*)&FurnaceBlockEntity::isFuel,(void*)&isfuel,(void**)&isfuel_);
	return JNI_VERSION_1_6;
}

**Comment by KenMizz** [comment]
bool (*isfuel_)(ItemInstance const*);
bool isfuel(ItemInstance const*iis)
{
	if(iis->getId()==1)
		return true;
	else return isfuel_(iis);
}
float (*getBurnDuration__)(ItemInstance const*);
float getBurnDuration_(ItemInstance const*iis)
{
	if(iis->getId()==1)
		return 10;
	else return getBurnDuration__(iis);
}
JNIEXPORT jint JNI_OnLoad(JavaVM*,void*)
{
	MSHookFunction((void*)&FurnaceBlockEntity::getBurnDuration,(void*)&getBurnDuration_,(void**)&getBurnDuration__);
	MSHookFunction((void*)&FurnaceBlockEntity::isFuel,(void*)&isfuel,(void**)&isfuel_);
	return JNI_VERSION_1_6;
}

**Comment by jakkti111** [comment]
Jakkti

**Comment by KenMizz** [comment]
@zhuowei
