### ISSUE TITLE
intent filter for shaders

### ISSUE THREAD

**Issue by TobySegar** [zhuowei/MCPELauncher#983]
Make intent filter for textures to not stack the textures. Make new intent filter for shaders with stacking. When kids try more and more texture packs at one point BL just crashes constantly and they cant handle clearing the cache and stuff like that. Make it so they are not stacking. Also make it so when they install BL for fist time and then use import activity, a texture would be active when they fire up  BL for the first time. Im the owner of a texture pack app that gave you over 1M downloads. You are posting bullshit on your twitter instead of reading it. The implementation of the things that im asking for should be really quick.

**Comment by DiegoGTRatty** [comment]
I wonder if something like a tutorial for first time users exists around the internet.

**Comment by zhuowei** [comment]
@vaoaboo Thank you for being honest. I understand that I have the responsibility to help users and developers, and I'm sorry that I haven't managed to meet expectations.

Latest beta fixes the imports ignored before first startup bug and adds REPLACE_TEXTUREPACK which deletes all the texture packs currently selected and replaces it with the single pack passed in; is that what you want?
Usage:
```
			Intent intent = new Intent("net.zhuoweizhang.mcpelauncher.action.REPLACE_TEXTUREPACK", 
				Uri.parse("file:///sdcard/testpack.zip"));
			startActivity(intent);
```

http://zhuoweizhang.net/MCPELauncher/MCPELauncherApp-release-beta.apk

**Comment by vaoaboo** [comment]
Thank you, that's exactly what I wanted. Don't get me wrong, you are doing a good job with BL but sometimes it's hard to get your attention. I understand that you're probably busy with other things, but at least check git issues once in a while. Although I have to admit since you included the git link into your release message on playstore there is a lot of pointless issues being created.
